### ISSUE TITLE
rebuild in option.add causing error 

### ISSUE THREAD

**Issue by tamaraRafid** [pytesNET/tail.select#108]
im trying to select option based on ajax response ... when the last parameter is "false"
the select dosen't show options but there is no error 
<img width="811" alt="Screen Shot 2019-09-01 at 3 37 26 PM" src="https://user-images.githubusercontent.com/33762430/64076523-aed47800-ccce-11e9-9ecc-78ffd9a8b1f7.png">
<img width="943" alt="Screen Shot 2019-09-01 at 3 37 09 PM" src="https://user-images.githubusercontent.com/33762430/64076539-d1ff2780-ccce-11e9-92be-5efce379c363.png">

**Comment by Calak** [comment]
Which version do you use?

And check this, there's a workaround.

**Comment by tamaraRafid** [comment]
im using 0.5.15 ..... check what ?

**Comment by Calak** [comment]
Forgot to paste the link, sry ;)
https://github.com/pytesNET/tail.select/issues/52
