### ISSUE TITLE
Programatically set selected option

### ISSUE THREAD

**Issue by Riaan-ZA** [pytesNET/tail.select#109]
How can I change the selected value using JS? Updating the select input's selected value doesn't seem to trigger a change in the tail select.

**Comment by rajwanur** [comment]
You can use `options.handle` to set values pragmatically. 

Lets you have the following select element 
```html
<select id="mySelect">
	<option value="1">Option 1</option>
	<option value="2">Another option</option>
	<option value="3">Third option</option>
	<option value="4">Another maybe</option>
</select>
```
And you have initialized tail.select 
```js
tail.select('#mySelect');
```

Now you if you want to select _third_ option, whose key is known to you. 
```javascript
let key = 3;
tail.select('#mySelect').options.handle("select", key, "#");
```
Pay attention to the third parameter in handle, which is used for colgroups. If you do not have colgroups, you have to use `"#"`. 

Please have a look at the [handle ](https://github.com/pytesNET/tail.select/wiki/Public-Methods#handlestate-key-group-_force)documentation for more details.

**Comment by RiaanZA** [comment]
Thanks @rajwanur

**Comment by SamBrishes** [comment]
Hellow,

thanks for your question and thanks to @rajwanur for pointing out the answer!

You can also use the alias `options.select("key", "#")`, which just calls the `handle()` method. 

I guess this issue can be closed, just re-open this issue again if something isn't clear or if you have another question about selecting options.

Sincerely,
Sam.
