### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by wira-sandy** [pytesNET/tail.select#112]
How to validate the select element. It ignore jquery validation

**Comment by SamBrishes** [comment]
Hellow,

thanks for your question. Which kind of validation do you mean?

The constructor of the `tail.select` class already validates, that the first parameter is either a selector (leading to one or more select elements) or a select element itself (including a HTMLCollection, NodeList or an Array for multiple select elements). Already instanced select elements also didn't get re-initialized, it just returns the respective instance itself again.

Sincerely,
Sam.
