### ISSUE TITLE
Can't buy coffee

### ISSUE THREAD

**Issue by thomasfedb** [pytesNET/tail.select#116]
Your Buy Me a Coffee is broken, payments are disabled!
![Screenshot from 2019-12-08 23-23-32](https://user-images.githubusercontent.com/193831/70391627-26265000-1a12-11ea-82f9-fd2364f815e2.jpg)

**Comment by SamBrishes** [comment]
Hellow,

thanks for your support. I really appreciate that!

I disabled the support ability, because I couldn't work on my projects for a long time. So I don't want to get money / coffees for doing nothing.

Sincerely,
Sam.
