### ISSUE TITLE
how correct use set method? , need examples in Docs

### ISSUE THREAD

**Issue by OnePeople** [pytesNET/tail.select#118]
Hello there,

if I have  
`let   countries  =  tail.select(".select-tail[name=countries]",tailConfig );`
   when I try
`countries.options.set({ 111:{value:'Some name'} }, true)`

I have result error:

```
tail.select.min.js:2 Uncaught TypeError: Cannot read property 'label' of undefined
    at p.options.set (tail.select.min.js:2)
    at <anonymous>:1:15
set @ tail.select.min.js:2
(anonymous)  
```

Also I trying

`temp1.options.set({label:'sdf', 34:{value:'Some name'} }, true)`
 
`temp1.options.set({ 34:{value:'Some name', label:'dd'} }, true)
`
also error

How correct this method use?

why not have example in docs?

**Comment by SamBrishes** [comment]
Hellow,

as written on the documentation of the [set() method](https://github.com/pytesNET/tail.select/wiki/Public-Methods#setoption-rebuild): 

> **.set(option, rebuild)**
> `option <HTMLElement>, rebuild <bool>`
> This method adds already existing <option> elements, which does "already exist" on the source select field [...]

The `set()` method is used internally for adding all existing / available `<option>` elements to the instance. Of course, you can use it too, but it requires you to add the new  `<option>` element manually to the respective source `<select>` field before calling `set()`. 

*(This behaviour will change in 0.6.0)*

## The `add()` method
The method you're searching for is called [`add()`](https://github.com/pytesNET/tail.select/wiki/Public-Methods#addkey-value-group-selected-disabled-description-rebuild) and can be called with multiple parameters for a single option or with a respective object. You can see both ways on this [jsfiddle example](https://jsfiddle.net/SamBrishes/ct8xna3k/8/) or below:

The first method looks like this:
```javascript
var select = tail.select("select", {
    search: true
});


// Only the first 2 parameters are requried.
//  @param1     The unique key (as used in the value attribute)
//  @param2     The inner options text
//  @param3     The respective option group (use `#` for ungrouped)
//  @param4     True if the item should be pre-selected, false to do it not.
//  @param5     True if the item should be pre-disabled, false to do it not.
//  @param6     The option description, if you enabled this feature.

select.options.add("key1", "Second Option", "#", false, false, false)


// [...]
```

The second method like this:
```javascript
/// [...]


// Pass multiple options at once
//  The only required object property is `value` all other ones can be ommited.

select.options.add({
    "key2": {
        value: "Third Option",
        group: "#",
        selected: false,
        disabled: false,
        description: null
    }
});
```

-----

Thanks for your suggestion, I'll add some examples to the documentation with v. 0.6.0.

Sincerely,
Sam.
