### ISSUE TITLE
initial a new SELECT after add table row with initiated tail-select

### ISSUE THREAD

**Issue by machanrk** [pytesNET/tail.select#119]
Hello, Merry Christmas!

I want to know is there any other method to initial a new "select"?
Here is what I am doing and is working:

     <script>
     $(document).ready(function(){

         var originalServiceRowHtml = $("#serviceTable").find("tbody tr").html();

         tail.select(".tail-select", {
                search: true
         });     
    
         $("#addService-btn").click(function() {
                var table = $("#serviceTable"),
                    rowClone = $("<tr/>").html(originalServiceRowHtml);
                table.find("tbody").append(rowClone);
                $(rowClone).find(".tail-select").addClass("no-tail");
                
                tail.select('.no-tail', {
                    search: true 
                });

                table.find(".no-tail").removeClass("no-tail");
          });
    });
    </script>
    <body>
        <....>
        <tr>
            <td>
                 <select class="tail-select" >
                      <option th:each="product : ${productList}" th:value="${product.id}" 
                           th:utext="${product.name}" >service</option>
                 </select>
            </td>
         </tr>
         <...>
    </body>

The page will load a <SELECT> and resolve the option from server at the beginning.
When user add a table row, I clone the row from the beginning which is not being tail.select.
Then when append to the body, I need to add a class "no-tail" to the "SELECT" for the cloned row, and initial the tail.select by tail.select(".no-tail"). After that, remove the class "no-tail".

I had tried many different approach, but fail. Such as

    tail.select($(rowClone).find("select"), {
        search: true
    });

Would you please give me advice for how to add table which containing the tail.select in the correct way?

Thank you so much.
Mark

**Comment by SamBrishes** [comment]
Hellow Merry Christmas,

each `<select/>` field must be initialized, especially if you add them later. So you can't clone a `tail.select` instance but you also don't need to add and remove a special class name to it.

The following code uses the jQuery binding of the `tail.select` library. [Here is a respective example](https://jsfiddle.net/SamBrishes/gnmbuze5/4/):

```javascript
var originalServiceRowHtml = $("#serviceTable").find("tbody tr").html();

tail.select(".tail-select", {
    search: true
});     

$("#serviceTable").on("click", "#addService-btn", function(){
    var table = $("#serviceTable");
    var clone = $("<tr/>").html(originalServiceRowHtml);
    
    table.find("tbody").append(clone);
    $(clone).find(".tail-select").tailselect({
        search: true
    });
});
```

Sincerely,
Sam.

**Comment by machanrk** [comment]
Sorry for the late reply.
Thank you for your advice!
