### ISSUE TITLE
How to add on event for dynamically created select

### ISSUE THREAD

**Issue by supreetSekhon** [pytesNET/tail.select#121]
In order to add tail.select on dynamically created elements I made a function and called that every time select list is created and it worked. Now the problem is I need to check if particular option is being selected or deselected. I added the "on" function but it does not work for dynamically created select lists. Kindly help. Following is my code:

```
function intializeselect(){
    var SelectField = tail.select(".task_assigned_to", {
        multiSelectAll: true,
        placeholder: "Select User",
        search: true,
        bindSourceSelect: true
    });
    SelectField.on("change", function(item,state){
        console.log("change called");
        console.log(item.key);
        console.log(item.option.parentElement.name);
    });
}
$(document).ready(function(){
	intializeselect();
});
```

I need this to work for dynamically created select lists as well. Error is

```
Uncaught TypeError: SelectField.on is not a function
    at intializeselect
    at HTMLButtonElement.<anonymous>
    at HTMLDocument.dispatch (jquery.js:4435)
    at HTMLDocument.elemData.handle 
```

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue. To solve your problem I need a few more informations

- Which version do you use?
- Add the line `console.log(SelectField);` after the `tail.select` initialization and post the output here.

Thanks.

Sincerely,
Sam.

**Comment by supreetSekhon** [comment]
Hi Sam,

Thanks a lot for replying back. Sorry for checking this so late as for that time I stopped working on the project and now starting again. 
As you mentioned version, I checked and realized I was using an older version. I updated the version and problem got solved.

Thanks and have a great day!!
Supreet

**Comment by supreetSekhon** [comment]
Hi Sam,

Thanks a lot for replying back. Sorry for checking this so late as for that time I stopped working on the project and now starting again.
As you mentioned version, I checked and realized I was using an older version. I updated the version and _**same problem again for dynamically created select lists.**_

Thanks and have a great day!!
Supreet

**Comment by supreetSekhon** [comment]
Hi Sam,

I solved the issue by sending id of select list as argument to the function in which it is initialized. 
```
function intializeselect(id){
				var SelectField = tail.select("#task_"+id,{multiSelectAll: false,placeholder: "Select",search: true,bindSourceSelect: true});
				SelectField.on("change", function(item,state){
						console.log("select changed");
				});
		}
```
Thanks!!
