### ISSUE TITLE
Translation: ka

### ISSUE THREAD

**Issue by spirtskhalava** [pytesNET/tail.select#122]
### All
-   "ყველას მონიშვნა"
### None
-   "ყველას გაუქმება"
### Select All
-   "ყველას არჩევა"
### Unselect All
-   "ყველას გაუქმება"
### No Options available
-   "ოფცია არ არის ხელმისაწვდომი"
### No Options found
-   "ოფცია ვერ მოიძებნა"
### You can't select more Options
-   "თქვენ არ შეგიძლიათ მეტი ოფციის არჩევა"
### Select an Option...
-   "აირჩიეთ ოფცია"
### Select up to :limit Options...
-   "აირჩიეთ :limit-ზე მეტი ოფცია"
### Type in to search...
-   "ძებნისთვის აკრიფეთ"
### This Field is disabled
-   "ველი გაუქმებულია"

**Comment by Lenivyy** [comment]
Hello,

thanks for translating. Will be implemented in upcoming major release.

~ Lenivyy

**Comment by SamBrishes** [comment]
Thank You! That's relly cool and will be released in 0.6.0!
