### ISSUE TITLE
Translation: lt

### ISSUE THREAD

**Issue by Apskaita5** [pytesNET/tail.select#124]
### All
-   "Visi"
### None
-   "Nei vienas"
### Select All
-   "Pasirinkti visus"
### Unselect All
-   "Atžymėti visus"
### No Options available
-   "Nėra pasirinkimų"
### No Options found
-   "Nepavyko rasti pasirinktimų"
### You can't select more Options
-   "Jūs negalite pasirinkti daugiau variantų"
### Select an Option...
-   "Pasirinkite variantą..."
### Select up to :limit Options...
-   "Pasirinkite iki :limit variantų..."
### Type in to search...
-   "Įrašykite paieškos teksto fragmentą..."
### This Field is disabled
-   "Šis laukelis išjungtas"

**Comment by Lenivyy** [comment]
Hello,

thanks for translatiing. Will be implemented in upcoming major release.

~ Lenivyy

**Comment by SamBrishes** [comment]
Thank You! That's relly cool and will be released in 0.6.0!
