### ISSUE TITLE
Not showing value when disabled

### ISSUE THREAD

**Issue by Apskaita5** [pytesNET/tail.select#125]
If a select is disabled it shows text "This Field is disabled" instead of the current value of the field. I think, it's a bug. But in case it's a feature, how to disable it and show current value?

**Comment by Lenivyy** [comment]
Hello,

A disabled select field does not submit on a HTML form, there is no real used "value", so it is either a feature nor a bug. 

Of course you can change the label attribute using the updateLabel method also if it is disabled:

```
let sel = tail.select("select");
sel.updateLabel(sel.e.querySelector("option:checked").innerText);
```

~ Lenivyy

**Comment by kavya164** [comment]
Hello, 

`let sel = tail.select("select");
sel.updateLabel(sel.e.querySelector("option:checked").innerText);`

I have used the above code which you suggested for the disabled field but, it's not working for a select disabled option, It is showing an error as Cannot read property querySelector of undefined
