### ISSUE TITLE
Total Selected Count Isse

### ISSUE THREAD

**Issue by ArtemKomazov** [pytesNET/tail.select#126]
![tail select issue](https://user-images.githubusercontent.com/61158269/76067316-d5ce7800-5f97-11ea-964e-d02e6d39d791.png)
This issue happens only for grouped & multiple select having select "All", "None" button.
If you click "None" button more than once for specific group section, total selected count will be decreased continuously.
If should be decreased one time with the count of specific group options, and should never be decreased continuously.

**Comment by Lenivyy** [comment]
Hello,

I know this bug already and has fixed them in the upcoming release. Thanks for posting.

~ Lenivyy
