### ISSUE TITLE
Sort item with key value and option name

### ISSUE THREAD

**Issue by machanrk** [pytesNET/tail.select#128]
Hi SamBrishes,
I want to sort the item with key values and the option name. 
I had tried the following with own sort function:
` function compareNumbers(a, b) {
    console.log("a: " + a);
    console.log("b: " + b);
      return a - b;
    }    `

 

    $(document).ready(function () {
        tail.select(".select", {
            search: true,
            placeholder: "...",
            sortItems: compareNumbers                   
            
        }); 
    }); `
`<option value="${key}">${name}</option>`

There is 2 questions:
1. is the setting correct?
2. how can i obtain the key and text for compare?

Thank you so much.

**Comment by Lenivyy** [comment]
Hello,

if you pass a function to the sortItems option, you will get all keys of the current group inside an array as first parameter. Which means you need to do something like

```
tail.select(".select", {
  sortItems: function(keys){ return keys.sort(compareNumbers); }
});
```

The function also contains the options object as this attribute, which means you can access all options methods directly. It is really bad design and does not work on optgroups, but if you want to sort them using the text too, you would need something like this

```
tail.select(".select", {
  sortItems: function(keys) { 
    let self = this;
    
    return keys.sort(function(a, b) {
      let opta = self.get(a, "#");
      let optb = self.get(a, "#");
      return opta.value - optb.value;
    });
  }
});
```

The sorting methods has been way improved in the upcoming release, but at the moment I guess this is the only way to achieve what you are looking for.

~ Lenivyy
