### ISSUE TITLE
How can I load dynamic list into the options tail.select

### ISSUE THREAD

**Issue by saharza** [pytesNET/tail.select#13]
I want to load a list of items form a REST call in to the tail.selcet.
Is it possible?

**Comment by SamBrishes** [comment]
Hellow,

yes it is, as shown in the 7th example on the current demonstration page, called ["A manipulatable Select Field"](https://github.pytes.net/tail.select/).

# Version 0.4.x
The current version offers the following method to add options during the runtime.

## Using .options.add()

```javascript
var selectField = tail.select("#my-select-field");

yourAjaxResponse(function(items){
    for(var item, i = 0; i < items.length; i++){
        item = items[i];
        selectField.options.add(
            item.key,               // Required: The unique option value
            item.value,             // Required: The options innerText
            item.group,             // Optional: The respective optgroup label
            item.selected,          // Optional: Boolean value to select this item
            item.disabled,          // Optional: Boolean value to disable this item
            item.description        // Optional: The option description, if enabled
        );
    }
});
```

# Version 0.5.x
The next major release gets published in a few days (or hours?) and allows also to set "a bunch" of options at once too:

## Using .config()
The following method will replace all options, which are previously set with the `items` option.

```javascript
var selectField = tail.select("#my-select-field", {
    items: {
        // This options gets replaced after the AJAX Call!
        
        uniqueKey1: "Any Option",   // Just set an Key + innerText
        uniqueKey2: {               // Set a complete structure
            value: "Other Option",
            group: "#",
            selected: false,
            disabled: false,
            description: "My Description"
        }
    }
});

yourAjaxResponse(function(items){
    selectField.config("items", items);
    
    // The options within `items` MUST use the same structure as above!
    // See `uniqueKey2` for example!
});
```

## Using .options.add()
The following method will add all additional options, without replacing.

```javascript
var selectField = tail.select("#my-select-field", {
    items: {
        // This options will remain!
        
        uniqueKey1: "Any Option",   // Just set an Key + innerText
        uniqueKey2: {               // Set a complete structure
            value: "Other Option",
            group: "#",
            selected: false,
            disabled: false,
            description: "My Description"
        }
    }
});

yourAjaxResponse(function(items){
    selectField.options.add(items);
    
    // The options within `items` MUST use the same structure as above!
    // See `uniqueKey2` for example!
});
```

Sincerely,
Sam.

**Comment by saharza** [comment]
Thanks for the quick response.
I am trying to load it with some static items but form some reason it duplicate the items
JSFiddle: https://jsfiddle.net/saharzjs/p40Lfh75/

**Comment by SamBrishes** [comment]
Hellow,

Oops, this is a ~feature~ bug! The `add()` method (which is also used on the items option) does only check if the optgroup does already exist or not. "Ungrouped" options uses a "pseudo" group called "#", which is not checked here. 

I will fix it in 0.5.0 too, if you need a prompt solution change [Line 1094](https://github.com/pytesNET/tail.select/blob/master/js/tail.select.js#L1094) 

FROM
```javascript
if(!(group in this.groups)){
```

INTO
```javascript
if(group != "#" && !(group in this.groups)){
```

Thanks for reporting.

Sincerely,
Sam.

**Comment by saharza** [comment]
Thanks.
When next major release gets published? 
Will it still be a beta version?

**Comment by SamBrishes** [comment]
I hope I can publish the new version on Tuesday, next week. And yes it is still beta, the first stable release will be 1.0.0.

**Comment by saharza** [comment]
Thanks.
Is there an option of limiting the UI (drop-down) items, to 50 for example, but still holding all items that
come form the server, for example 2000?
And if so, is it possible to also perform the search text logic on all the 2000 items and not only for the items in the UI (drop-down)?

**Comment by SamBrishes** [comment]
There is currently no way to limit the "shown" options within the tail.select dropdown field to 50 items, per sé. But in Version 0.5.0 you can use the `cbLoopItem` option, which allows you to hook a custom function to the render process.

 

This option is already implemented, but just allows an Element object as returning value. In the next version you can also return `null` to skip the respective option or `false` to "escape" / "break" the rendering loop at all. I will provide an specific example on the new demonstration page, as well as on the "How To" page on the GitHub Wiki.

 

To your second questions: Yes, it search through all 2000 options, because the "search" function applies a RegExp search to the **source** `<select>` field (it uses the `<select>`.innerHTML string). And each option gets added to the source `<select>` field.

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your help, version 0.5.0 has been released now. Issue closed.

Sincerely,
Sam.

**Comment by venkatdev22** [comment]
After adding new options through ajax response Items are getting added to existing options. But, search seems to be now working. Below is my select configuration
// select configuration 

    var ulmLastMultiple = tail.select(".ulmLastMultiple", {
        search: true, multiSelectAll: true, placeholder: "Select options"
    });

//Ajax success
success: function (data) {
               var newAddItem = [];
                data.forEach(function (item) {
                                   newAddItem.push({ key: item.value, value: item.name, description: "" })
                });

                //console.log('newAddItem', newAddItem);
                ulmLastMultiple.options.add(newAddItem);
    
            }
