### ISSUE TITLE
Tags duplicated when preselected

### ISSUE THREAD

**Issue by benlane** [pytesNET/tail.select#14]
When using the select container and pre-selecting items the tags get duplicated.

https://codepen.io/benlane/pen/mQxgap

**Comment by SamBrishes** [comment]
Hellow, 

Thanks for reporting. This bug will also get fixed in the new update (which should be available in a few days)!

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your help, version 0.5.0 has been released now. Issue closed.

Sincerely,
Sam.
