### ISSUE TITLE
Item description property is a must property?

### ISSUE THREAD

**Issue by saharza** [pytesNET/tail.select#15]
Hello,

I just  updated to the new version 0.5.2 and I am getting this error:

> - Uncaught TypeError: Cannot read property 'length' of undefined
>     at tailSelect.options.add (tail.select.js:1076)

it comes from the add() method from this line:

            `if(description.length && description.length > 0){
                option.setAttribute("data-description", description);
            }`

I am initializing the tail.select with array of items without a description property for each item.
I wanted to know if this is a require filed now?

**Comment by SamBrishes** [comment]
Hellow,

thanks for the report and sorry for this bug. 

The description setting on the item is still optional, this bug will get fixed really soon.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
This issue has been fixed in the new release (0.5.3).

Sincerely,
Sam.
