### ISSUE TITLE
Import with webpack

### ISSUE THREAD

**Issue by dixpac** [pytesNET/tail.select#158]
Hey!

Awesome library 👍 , researching to migrate from `slim-select` to `tail.select`. 

I've small issue on `import`. I'm using webpack(to be exact Rails Webpacker), whatever I try in import I always get `ReferenceError: tail is not defined` error..

Any tips how to `import` or `require` tail.select?

I've installed the package with: `yarn add tail.select --save`

**Comment by mortadda** [comment]
`import * as tail from 'tail.select/js/tail.select';

window.tail = tail;
`
