### ISSUE TITLE
When clicking on "Unselect All" button only the last item is unchecked

### ISSUE THREAD

**Issue by saharza** [pytesNET/tail.select#16]
Hi,

I am using version 0.5.2 and I am getting an error when clicking on the "Select All" button and then clicking on the "Unselect All" button.
This is the error:

> Uncaught TypeError: Cannot read property 'group' of undefined
>     at tailSelect.updatePin (tail.select.js:724)
>     at tailSelect.update (tail.select.js:627)
>     at tailSelect.callback (tail.select.js:430)
>     at tailSelect.options.handle (tail.select.js:1198)
>     at tail.select.js:1254
>     at Array.forEach (<anonymous>)
>     at tailSelect.options.all (tail.select.js:1253)
>     at HTMLButtonElement.<anonymous> (tail.select.js:557)

it's the updatePin() method when trying to get the prev item from the last item in tail.select.options:

> var grp = this.dropdown.querySelector("ul[data-group='" + item.group + "']"),
                    **prev** = this.options[item.index-1], found = false;
                while(**prev**.group == item.group){

The prev item is undefined.

**Comment by SamBrishes** [comment]
This issue has been fixed in the new published release.

Sincerely,
Sam.
