### ISSUE TITLE
when sourceBind option true dropdown becomes unusable

### ISSUE THREAD

**Issue by benlane** [pytesNET/tail.select#17]
https://codepen.io/benlane/pen/eQPWyb 

When you select this option then you can't select any options in the drop-down. I think there is a circular event issue.

**Comment by SamBrishes** [comment]
Hellow,

thanks for reporting, I could fix this issue. And you're right I "trigger" the event which is listening for the respective input on the source select field on my own. The update is coming really soon!

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
This issue has been fixed with the new release: [jsFiddle](https://jsfiddle.net/SamBrishes/cmjw6134/3/).

Sincerely,
Sam.
