### ISSUE TITLE
"Select All" / "Unselect All" throws TypeError with search text 

### ISSUE THREAD

**Issue by saharza** [pytesNET/tail.select#18]
I am using version 0.5.2, when I am entering a search text and clicking on "Select All" button the items 
that inside select that fit to the search text do not get selected.
also there is an error:

> tail.select.js:720 Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
>     at tailSelect.updatePin (tail.select.js:720)

And when I am clicking the "Unselect All" I get this error:

> Uncaught TypeError: Cannot read property 'group' of undefined
>     at tailSelect.updatePin (tail.select.js:724)

this is a fiddler example: 
-  [jsfiddle](https://jsfiddle.net/saharzjs/p40Lfh75/)

Enter a search text: "sss"  and then click on "Select All" and then click on "Unselect All" .

**Comment by SamBrishes** [comment]
Hellow,

thanks again! This issue could also be fixed (the `multiPinSelected` option has no effect anymore on "search queries"). The update will be released very soon.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
This issue has been fixed with the new release: [jsFiddle](https://jsfiddle.net/SamBrishes/fuo5tmdc/3/).

Thanks.

Sincerely,
Sam.

**Comment by saharza** [comment]
just notice that if I am entering search text: "ssss"  (4 's' chart's)
I am getting only one item in dropdown options but when I am clicking the "Select All" button 
the selected count number is 2.
see example in the jsFiddle that you add:
[jsFiddle ](https://jsfiddle.net/SamBrishes/fuo5tmdc/3/)
