### ISSUE TITLE
Unnecessary scrollbar and z-index on hover

### ISSUE THREAD

**Issue by ashucg** [pytesNET/tail.select#19]
### Scrollbar
There is a unnecessary scrollbar, as can be seen here:
![seen here](https://user-images.githubusercontent.com/11291284/49202784-d0b16f00-f3cb-11e8-836a-c8268d8098ef.png)

I would suggest you to:
- Remove padding for `.tail-select .select-dropdown .dropdown-inner` selector
- Remove `-2` from [tail.select.js#L499](https://github.com/pytesNET/tail.select/blob/master/js/tail.select.js#L499)

### z-index
I think there is no need to increase z-index for `.tail-select:hover` selector:

![z-index](https://user-images.githubusercontent.com/11291284/49203941-20923500-f3d0-11e8-83dc-9b9fd72475d3.png)

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait and thanks for reporting this design behavior.

The current master branch now already contains a respective fix, which consists of a JS based solution for the scrollbar calculation and some stylesheet changes for the z-index issue.

The update gets published during the next week.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Version 0.5.4 has been released just now and contains a Fix for this issue.

Sincerely,
Sam.
