### ISSUE TITLE
Searching when data-description containes > char

### ISSUE THREAD

**Issue by tomasKucera** [pytesNET/tail.select#2]
Consider this HTML code:
```
...
<option data-description="Category > Subcategory">Subcategory</option>
...
```
Then searching for string "sub" (for example) doesn't work.
When removing the ">" char, then searching works.

**Comment by SamBrishes** [comment]
Hello,

Thanks.

This issue is caused by the used search regex which doesn't accept > within the HTML tag.

I will fix this as quickly as possible.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Version 0.3.5 changes the `<` `>` characters into the respective HTML Entities `&lt;` `&gt;` and should fix your described issue. Hotfix 0.3.6 changes also the complete RegExp Part to directly pass the <> characters (including also inner HTML elements) within all attributes (so it's no longer limited to the `data-description`).

Sincerely,
Sam.
