### ISSUE TITLE
Option/Method to change locale strings

### ISSUE THREAD

**Issue by ashucg** [pytesNET/tail.select#20]
It would be nice to have it as an option or a method similar to `tail.select.strings.register()` and in the mean time you can mention it in the wiki that locale strings can be changed using `tail.select.strings[locale][key] = <string>`

**Comment by SamBrishes** [comment]
Hello,

sorry for the long wait, I'm currently really busy. The current master branch contains the unreleased new Update, which offers the new method `tail.select.strings.modify(locale, id, string)`. This method allows to modify existing (or adding completely new!) strings on **already registered** locales.

You can pass the respective string id (for example "placeholderMulti") as second parameter or an object with multiple `string_id: "new_string"` pairs.

Thanks for your request, the update gets published during the next week.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Version 0.5.4 has been released just now and contains the request described in this issue!

Sincerely,
Sam.
