### ISSUE TITLE
just notice that if I am entering search text: "ssss"  (4 's' chart's)

### ISSUE THREAD

**Issue by saharza** [pytesNET/tail.select#21]
When I am entering a search text: 'ssss'  (4 's' chars) then 
I am getting only one item in dropdown options but when I am clicking the "Select All" button 
the selected count number is 2.
see example in the jsFiddle that you add:
[jsFiddle ](https://jsfiddle.net/SamBrishes/fuo5tmdc/3/)

_Originally posted by @saharza in https://github.com/pytesNET/tail.select/issues/18#issuecomment-442751917_

**Comment by SamBrishes** [comment]
Hellow,

I'm really sorry for the long waiting time, I'm currently really busy. I could fix your issue, you can download the current master branch for the time being. During next week I will also publish a respective Release (0.5.4), which will contain this fix too.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Version 0.5.4 has been released just now and contains a Fix for this issue.

Sincerely,
Sam.
