### ISSUE TITLE
[UPDATE] New Stylings and more for v0.6.0

### ISSUE THREAD

**Issue by SamBrishes** [pytesNET/tail.select#29]
Hellow,

I'm currently working on the next Major Release (version 0.6.0), which contains just a few improvements and changes on the JavaScript side. The new Version rather focuses on the Less and CSS environment, which WILL break the current "way to style".

ClassNames instead of files
---------------------------
The current version allow to change the colour scheme by using different Stylesheets only (which resulted in 6 different files for each bootstrap theme). This isn't really efficient, especially when you try to implement different colours of one theme on the same page.

So Version 0.6.0 will handle the different colour schemes using classNames (as known from bootstrap too). So each theme (Default, Modern, Bootstrap2, Bootstrap3 and Bootstrap4) will uses respective additional names, which you need to include / activate on the `tail.select` constructor.

### Example
```javascript
tail.select("select", {
    classNames: "select-danger"     // Directly adds this class name
});
```

or
```html
<select class="select-danger">
    <!-- Your Options-->
</select>
<script type="text/javascript">
    tail.select("select", {
        classNames: true            // Will Copy the "source" class names
    });
</script>
```

Bootstrap Shims
-----------------
I don't know what `Shim` means, but apparently it means a "plugin" or "extension" for a (Bootstrap) Framework. So I hope that is right, because our Less files will now be "Shim"-able. So you can "import" your `variables.less` Bootstrap configuration file after the "fallback" variables (for users who don't want to use Bootstrap, but still want to use the bootstrap theme) to compile the CSS files with your own stylings.

More additional Classes
------------------------
I'm not using Bootstrap for my own projects, however some "settings" are still really useful. Like the possibility to increase and decrease the single buttons and elements. I want to offer a similar environment, so each theme will probably offer the following additional class names:

### Sizes
This settings just changes the width (and maybe the font size) of the label element, but keeps the width (250px, if not changed via the `width` option).

`select-large`
`select-default`
`select-medium`
`select-small`

### Widths
This settings just allows to quickly adopt the width of the respective element, if not changed with the `width` settings.

`select-full-width` (100%)
`select-half-width` (50%)
`select-large-width` (500px)
`select-default-width` (250px)
`select-medium-width` (125px)
`select-small-width` (75px)

### Colours
As mentioned above, the respective colours. My own themes (Default and Modern) may just offer the default colour scheme (white) and a dark one using `select-black` as additional class. The Bootstrap ones will contain the known classes (`select-primary`, `select-info`, `select-danger`, `select-warning`, `select-success` and `select-inverse`) and maybe some more ;).

Bootstrap4
-----------
The new bootstrap 4 theme will change the "default" colour scheme to something which should look like the new "custom-select" field. Of course, the existing ones will be kept, just moved to an additional class name.

**This may won't work on Bootstrap 4**, because we're using Less and Bootstrap 4 SCSS.

More ICONS
-------------
Our original **tail.select** jQuery plugin used the awesome [feather](https://feathericons.com/) IconSet instead of GitHubs Octicons. So I will re-implement this icons too, but maybe as optional setting within the Less file only. So the main / core CSS Stylesheets will keep the Octicons at the moment.

Better Less Environment
-------------------------
The Less files itself will also be improved and offer a better and configurable environment (at least on my own themes, the bootstrap ones look a bit weird, I guess).

-----------------------

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

`select-full-width` will just use 100% of the parent container, so if the parent is responsive designed, then yes. A X-Button should also be possible for the search field, I will keep this in mind. Thanks.

I'm not really into Unit-Testing right now, and I also don't have any respective environment for this. So, no, there will be no tests at the moment.

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Hi, I have data which includes selected and unselected entries in a specific order. The problem is that the selected ones always stays at the end of my list. Is there also a way to disable the sort? I want the originally order such as I insert the entries.
Orginal order:
- Entry 1
- Entry 2 (selected)
- Entry 3 (selected)
- Entry 4
After initialization with tail.select:
- Entry 1
- Entry 4
- Entry 2 (selected)
- Entry 3 (selected)

**Comment by SamBrishes** [comment]
Hellow,

I opened a new issue with your question, please look at #31. Thanks!

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Is it possible to get all selected entries? I can't find something related to that in the documentation.

**Comment by SamBrishes** [comment]
Hellow, 

@bennymeier You can use the `selected` variable of the tailOptions class, which contains all selected `<option>` elements (stored as Array)

You can access them through the `options` variable of the respective tail.select instance, like:

`tail.select("#my-select").options.selected`

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow @bennymeier,

## First Issue
yes I will try to write the `tail.select` themes as responsive as possible.

## Second Issue
I tried the same, so I attached a function to the `cbComplete` option and I can access the pre-selected options array as mentioned above. The used Code (live demo @ [JS Fiddle](https://jsfiddle.net/SamBrishes/Lpfh6eo4/)):

```javascript
var input = document.getElementById("my-input");
tail.select("select#my-select", {
    cbComplete: function(){
        this.options.selected.forEach(function(item){
            if(input.value != ""){
                input.value += ", ";
            }
            input.value += item.innerText;
        });
    }
});
```

## Third Issue
The `.finder()` option is a [generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) (A pseudo-generator on the default edition, and a real one on the ES6 version). So you need to use `.finder()` within a while loop like

```javascript
var select = tail.select("#my-select"), item;
while(item = select.options.finder()){
    // Handle Option
}
```

You can also use the `.find()` method, which returns all respective options as ARRAY.

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Thanks! 
Related to the 1st issue: Can you add user-select: none; to some elements? If I open and close the list fast, it marks text.

Related to the 2nd issue: I got the wrong this context, my fault.

Related to the 3rd issue: I don't get it but I use the find() method now.

4rd issue/suggestion: I got hundreds of names and there are some same names which don't show up on the list. Is it because the value is the same? How is it possible to add duplicate entries to the list? Can you add a data-id or something like that?

5th issue: Your english translations should be in lowercase.
`actionAll: "Select all"
actionNone: "Unselect all"
all: "All"
disabled: "This field is disabled"
empty: "No options available"
emptySearch: "No options found"
limit: "You can't select more options"
none: "None"
placeholder: "Select an option..."
placeholderMulti: "Select up to :limit options..."
search: "Type in to search..."`

Suggestion: Is it possible to overwrite the language object? For an empty search result I would prefer "No results found".

**Comment by SamBrishes** [comment]
Hellow @bennymeier,

## IV. Issue
There is already something like an `data-id`, it's called `value`. [Here is an example on jsFiddle](https://jsfiddle.net/SamBrishes/3ot4hg5q/12/).

## 5. Issue
Thanks, I may will change this in the next major release (`actionAll` and `actionNone` aren't available anymore in 0.6.0+). 

## 6th Issue
The language strings can be easily adapted globally as well as per instance. [Check out the same example](https://jsfiddle.net/SamBrishes/3ot4hg5q/12/), which shows both ways. **Note** Version 0.5.5 currently contains the bug, that `empty` is used instead of `emptySearch` on empty search queries. This gets fixed in 0.6.0 too.

The code
```javascript
/*
 |	CHANGE THE LANGUAGE STRINGS GLOBALLY
 */
tail.select.strings.modify("en", "placeholder", "Select Spyro");

/*
 |	CHANGE THE LANGUAGE STRINGS PER INSTANCE
 */
tail.select("select", {
	search: true,
    cbComplete: function(){
    
    	// Language Strings are stored in `__`
        this.__.empty = "No results found";
    }
});
```

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Thanks for your fast answers all the time. Do you remove the buttons actionAll and actionNone or just the translation for it?! I like the feature and I need it often. So please keep it 👍

**Comment by SamBrishes** [comment]
No Problem.

Don't worry I just remove the translations, the buttons will move onto the search input field and use the `all` and `none` strings. As shown on this GIF ([Source Tweet](https://twitter.com/pytesNET/status/1083259319519461376)):

![tail-select](https://user-images.githubusercontent.com/31392477/51388396-92ae0d00-1b29-11e9-9f9b-52760069e3c5.gif)

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Is there a way to add an image? I know img-tags are not allowed within an option-tag but maybe there is another way?
I want something like this:
![Mail dropdown menu](https://i.imgur.com/3xTjZpg.png)

**Comment by SamBrishes** [comment]
Hellow @bennymeier,

theoretically it is possible, but it requires a custom rendering. I wrote a small example, check out [this CodePen](https://codepen.io/sambrishes/pen/NoLVJv). There I use [blueimps MD5 JavaScript](https://github.com/blueimp/JavaScript-MD5) implementation to fetch the respective Gravatars. The used code:

```javascript
var yourAvatarFunction = function(mail){
    var hash = md5(mail.trim().toLowerCase());
    return "<img src='https://www.gravatar.com/avatar/" + hash + "' />";
}

// tail.select
tail.select("select", {
    width: "300px",
    cbLoopItem: function(item, group, search){
        var li = document.createElement("LI");
        li.className = "dropdown-option" + (item.selected? " selected": "") + (item.disabled? " disabled": "");

        // Get Name and eMail
        if(search && search.length > 0 && this.con.searchMarked){
            var name = item.value.replace(new RegExp("(" + search + ")", "i"), "<mark>$1</mark>"),
                mail = item.key;
        } else {
            var name = item.value,
                mail = item.key;
        }

        // Get Avatar
        var avatar = yourAvatarFunction(mail);

        // Add Content
        li.innerHTML = "<div class='item-inner'>"
                     + "    <div class='item-avatar'>" + avatar + "</div>"
                     + "    <div class='item-text'>"
                     + "        <span class='text-name'>" + name + "</span>"
                     + "        <span class='text-mail'>" + mail + "</span>"
                     + "    </div>"
                     + "</div>"
        return li;
    }
});
```

![select](https://user-images.githubusercontent.com/31392477/52808230-ab103980-308d-11e9-99ee-710471a2ac5c.PNG)

The code requires also a custom styling (as shown in the CodePen).

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Wow, thanks a lot! That's exactly what I need. :flushed:

**Comment by bennymeier** [comment]
Are there any news about the release of v0.6.0?

**Comment by SamBrishes** [comment]
Hellow,

not yet, I'm currently really busy with a [Bludit Plugin](https://github.com/pytesNET/snicker) and with my real life. But as soon as I have a bit air I will update the tail.select script as fast as possible.

Sorry for that.

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Hi,
I got two questions.

**Nr. 1:** Is there a way  to remove all entries from the list and load new entries into with ajax?
I deleted all entries in the hidden <select></select> field and reloaded the list then it works.
But is this the way to go?

**Nr. 2:** Is there an eventlistener for the search field on input? If so, I didn*t find it. So I added one manually.

**Comment by SamBrishes** [comment]
Hi,

### Erste Frage
Es gibt jetzt keine "offizielle" Methode alle Items auf einmal zu löschen / zu ersetzen. Eine mögliche Variante allerdings wäre es, wie in deiner 3. Frage angemerkt, über `<select>.innerHTML = ""` sämtliche Optionen zu löschen, einen reload durchzuführen und die neuen Items darauffolgend hinzuzufügen.

Da bei einem Reload die gesamte Instanz gelöscht und neu erstellt wird "schließt" sich das dropdown natürlich und öffnet sich daraufhin auch nicht erneut. Nach ein wenig herumtricksen gibt es theoretisch die folgende Möglichkeit ([Die du auch hier testen kannst](https://jsfiddle.net/SamBrishes/ugy0t2qm/22/)):

```javascript
var select = tail.select("select", {stayOpen: true});
var button = document.querySelector("button");

var ajax = function(){
    /*
     |	HIER KANNST DU DEINE AJAX FUNKTION HINZUFÜGEN
     |	ICH NUTZE ERSTMAL LEDIGLICH EINEN KLEINEN TIMEOUT
     */
    setTimeout(function(){
    	select.e.innerHTML = "";
        select.options = new tail.select.options(select.e, select);
        select.options.add({
            "a": {value: "Neuer Eintrag 1" },
            "b": {value: "Neuer Eintrag 2" },
            "c": {value: "Neuer Eintrag 3" },
            "d": {value: "Neuer Eintrag 4" },
            "e": {value: "Neuer Eintrag 5" }
        });
    }, 1500);
}

button.addEventListener("click", function(event){
    event.preventDefault();
    ajax(); // Deine AJAX Funktion
});
```

### Zweite Frage
Auch hier gibt es aktuell keine direkte Möglichkeit, aber danke für die Info, dass werde ich auf jeden Fall auf meine Liste setzen. Bis dahin kannst du allerdings das folgende kleine Snippet nutzen, um auf das Suchfeld zuzugreifen ([Kleine Demonstration](https://jsfiddle.net/SamBrishes/jb14dL78/4/)):

```javascript
var select = tail.select("select", {
    search: true,
    cbComplete: function(){
        var search = this.search.querySelector("input");
        search.addEventListener("input", function(event){
            // Handle Search Field
        });
    }
});
```

### Dritte Frage
In der ersten Frage findest du bereits einen kleinen Ansatz um zu verhindern, dass sich das Dropdown Feld schließt. Ich werde aber vermutlich eine bessere `.reload()` Funktion implementieren, die das ganze wesentlich vereinfachen wird.

Die magische 3 für die Suchfunktion ist aktuell hardkodiert im Quellcode. Theoretisch könnte man das umgehen, indem man den Code der 2. Antwort nutzt und wie folgt ausbaut. Allerdings wäre eine direkte Option dafür auf jeden Fall besser.

```javascript
var select = tail.select("select", {
	search: true,
	cbComplete: function(){
    	var search = this.search.querySelector("input"), self = this;
        search.addEventListener("input", function(event){
    		self.query.call(self, this.value);
        });
    }
});
```

Danke für die Anmerkungen!

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Vielen Dank! Mir ist noch etwas aufgefallen, wenn man auf das onchange-Event reagiert mit this.tail.on("change", () => {}); und man klickt auf den _Select All_-Button, obwohl schon alle selektiert sind, wird das Event trotzdem getriggert, obwohl es eigentlich keine Änderungen gegeben hat. Andersrum natürlich genauso.

Könnte man noch hinzufügen, dass ein Klick auf _Select All_ oder _Unselect All_ nur einmal das onchange-Event triggert?
