### ISSUE TITLE
Readability when same options occur

### ISSUE THREAD

**Issue by tomasKucera** [pytesNET/tail.select#3]
I have a tree of product categories in furniture website separated by producer's names.
When I want to filter categories by a subcategory name, I am geeting this:
http://screens.zvladnu.cz/1/chrome_2018-10-11_16-57-48.png

So I can't see the path to the final category.
I could use "data-description" field, but maybe here I would prefere displaying of full path directly:
Example: "Adidas > Man > Shoes > Red"

Would it be possible to add option for this?

**Comment by SamBrishes** [comment]
Thanks for the Request, and yeah that should be no problem. 

I'm currently working on Version 0.4.0, which allows to configurate and manipulate the dropdown list itself instead of just sorting them. But I try to add your feature before the new release.

But one Question: What do you mean with the full path? Is this just a single `<optgroup label="Adidas > Shoes > Men > Red">` element or do you use nested `<optgroup>`s to achieve this. Because the second way is not officially standardized by w3, as far as I know and tail.select currently shouldn't support nested groups either.

Sincerely, 
Sam.

**Comment by tomasKucera** [comment]
Opps, you're right. Our nesting is done by spaces, so it looks like:
`<option>   Text</option>`

And sure, in this case it's nonsense to create nesting by this proprietal formatting.
But it would be good having an option for manipulations with text. And ideally setupable for standard mode and search mode separately.
Because our problem appears only at searching.

Otherwise it's a perfect library! Thank you very much!

**Comment by SamBrishes** [comment]
Thanks, i'm glad that you like it. ^^

In this case a callback function to configure the dropdown list / the displayed items should be the best way to handle this. I will try to find a solution at least in version 0.4.0. First I fix your Issue described in #4

Sincerely, 
Sam.

**Comment by SamBrishes** [comment]
Version 0.4.0 shows now the optgroup elements also in the search-view, but also allows to manipulate the dropdown list items and groups itself. Therefore I wrote a small new example (on the end of the demonstration page), according to your example (linked in #4). 

The new example converts spaces " " into "&amp;nbsp;&amp;nbsp;" to create a nested view and also shows "the full path" on search. The respective callback code:

```javascript
tail.select(".nested-selectable", {
    search: true,
    descriptions: true,
    multiSelectAll: true,
    cbLoopItem: function(item, optgroup, search){
        var li = d.createElement("LI");
            li.className  = "tail-dropdown-option";
            li.className += (item.selected)? " selected": "";
            li.className += (item.disabled)? " disabled": "";

        // Show "Path" on the Search-View only
        if(search){

            // The current Option Position (2 spaces -> +1 Position)
            var pos = item.option.innerHTML.search(/[^\s]/i)/2;

            // Create a New Path Element
            var path = d.createElement("SPAN"), 
                text = [], 
                element = item.option; // The source <option> Element

            // Get Full Path
            var i = 0;
            while(element = element.previousElementSibling){
                if(i++ >= pos){
                    break;
                }
                text.push(element.innerText);
            }
            path.innerText = text.reverse().join(" > ");
            path.style.cssText = "color:#707478;display:block;font-size:10px;line-height:14px;";

            // Add Path and Item Text
            li.innerHTML += path.outerHTML;
            li.innerHTML += item.value.replace(new RegExp("(" + search + ")", "i"), "<mark>$1</mark>");
        } else {

            // Convert " " into "&nbsp;&nbsp;"
            li.innerHTML += item.option.innerHTML.replace(/ /g, "&nbsp;&nbsp;");
        }

        // Inner Description
        if(this.con.descriptions && item.description){
            li.innerHTML += '<span class="tail-option-description">' + item.description + '</span>';
        }
        return li;
    }
})
```

**Comment by tomasKucera** [comment]
Only small notice:
`var li = d.createElement("LI");`
As you use "d" variable in the showcase, I recommend you to replace it by "document". Otherwise it returns an error.

**Comment by tomasKucera** [comment]
The mistake is also here in the latest example: https://github.pytes.net/tail.select/

**Comment by SamBrishes** [comment]
Oops, sorry. My demonstration environment assigns `document` to the variable `d`, but that shouldn't be part of the example code of course.

Thanks, I edited my answer and will update the demonstration with 0.4.1.

**Comment by jmleighton** [comment]
Hello!
I'm having a basic problem. How can I get all selected elements?
Thanks!

**Comment by SamBrishes** [comment]
Hellow @jmleighton,

The `<tail.select>.options.selected` class variable contains all selected `<option>` elements.

```javascript
var mySelect = tail.select("#select");

console.log(mySelect.options.selected); // Returns an array with all selected options
```

Another example can be found [on this jsFiddle](https://jsfiddle.net/SamBrishes/Lpfh6eo4/4/), which writes each selected option element into another input field.

Sincerely,
Sam.

**Comment by jmleighton** [comment]
Thanks!!

**Comment by jmleighton** [comment]
Hello again! I have another question.
How can I initialize the select with all values selected? 
Thanks for the patient!

**Comment by SamBrishes** [comment]
Hello @jmleighton.

You can use the `selected` attribute on each available `<option>` element (which would be the preferred HTML way). But you can also handle this using the `<tail.select>.options.all` method (using "select" as first argument) within the `cbComplete` callback option (which gets called every time the **tail.select** instance gets (re-) initialized) or after the initialization if you want to select the values just once at the beginning.

Call it every time the **tail.select** gets initialized ([jsfiddle](https://jsfiddle.net/SamBrishes/rvkp45sb/5/)):
```javascript
var select = tail.select("#select", {
    cbComplete: function(){
        this.options.all("selected");
    }
});
```

Call it once:
```javascript
var select = tail.select("#select");
select.options.all("select");
```

Sincerely,
Sam.

**Comment by jmleighton** [comment]
Thanks a lot, it was very helpfull!
