### ISSUE TITLE
Wrong order on selected items

### ISSUE THREAD

**Issue by SamBrishes** [pytesNET/tail.select#31]
Hi, I have data which includes selected and unselected entries in a specific order. The problem is that the selected ones always stays at the end of my list. Is there also a way to disable the sort? I want the originally order such as I insert the entries.
**Orginal order:**
- Entry 1
- Entry 2 (selected)
- Entry 3 (selected)
- Entry 4

**After initialization with tail.select:**
- Entry 1
- Entry 4
- Entry 2 (selected)
- Entry 3 (selected)

_Originally posted by @bennymeier in https://github.com/pytesNET/tail.select/issues/29#issuecomment-453423974_

**Comment by SamBrishes** [comment]
Hellow,

are the items already within the select field or do you add them using the `items` option or with the `tailOptions` (`select.options.add`) class? Because I tried to force the same behaviour, but all tree possibilities keeps the current order as shown [on this jsFiddle](https://jsfiddle.net/SamBrishes/ah4gLxsj/6/).

Please show me the used options from the respective select field too.

Thanks.

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Ooops, my fault Im sorry. It was my condition which was wrong in XSLT. So the order was among each other. You can delete or close the issue.

**Comment by SamBrishes** [comment]
Okay, no problem.
