### ISSUE TITLE
Different values but same innerText - selected doesn't work

### ISSUE THREAD

**Issue by bennymeier** [pytesNET/tail.select#33]
My settings:
`        const that = this;
        this.tail = select(this.selectElement, {
            cbComplete() {
                    that.fillHiddenField(this.options.selected);
            },
            multiContainer: false,
            multiSelectAll: true,
            multiple: true,
            search: true,
            sortItems: "ASC",
        });`

My list:
- `<option data-key="Test" data-group="#" value="Test-1">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-2">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-3">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-4">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-5">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-6">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-1" selected="">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-2" selected="">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-3" selected="">Test</option>`
- `<option data-key="Test" data-group="#" value="Test-4" selected="">Test</option>`

If I change the innerText to the values, then it works. But if the the innerText are all the same the selected items don't show up on the list as selected.

**Comment by SamBrishes** [comment]
Hellow,

You mentioned "Different Values", but this isn't true. Your list uses "Test-1" up to "Test-4" twice (at the beginning and the ending of the list). If you change the values of the last 4 items, it will work [as shown on this jsfiddle](https://jsfiddle.net/SamBrishes/o8edfnbk/6/).

The **tail.select** script cannot handle multiple used values **within the same group**. So you need to change the value itself (make it unique) or move it in another group (using a parent `<optgroup>` element).

Sincerely,
Sam.

**Comment by bennymeier** [comment]
Oops again my fault. Sorry 👍
