### ISSUE TITLE
[0.6.0][Plugin] Collapsible groups

### ISSUE THREAD

**Issue by jayakrishnang** [pytesNET/tail.select#36]
Don't know if I'm asking for more, but it would be lovely to have a collapsible groups so as to handle long groups. Would make it neat!

**Comment by SamBrishes** [comment]
Hellow,

thanks for the request. Collapsible Groups sounds after a good function and also a good first plugin for the future API. I'll try to implement such a feature.

Sincerely,
Sam.

**Comment by jayakrishnang** [comment]
Thanks! 👍

**Comment by SamBrishes** [comment]
Done, will be published in the "select-columns" plugin in 0.6.0.
