### ISSUE TITLE
Remove default options sorting

### ISSUE THREAD

**Issue by adrienlamotte** [pytesNET/tail.select#37]
Hello,

By default, tail.select seems to sort my options... Even if the `sortItems` option is set to false.
Any way to keep the default order of my options ?

![image](https://user-images.githubusercontent.com/2301651/54634753-2137ff80-4a83-11e9-8659-b9df673821b3.png)

Thank you !

**Comment by SamBrishes** [comment]
Hellow,

thanks for reporting this bug! I could fix this issue and released the Bugfix as Version 0.5.7. Please try the updated version.

Thanks.

Sincerely,
Sam.

**Comment by adrienlamotte** [comment]
Thank you @SamBrishes , I tried the 0.5.7 and it's fixed :-)

**Comment by SamBrishes** [comment]
Perfect :3
