### ISSUE TITLE
How can i create multiple instances dynamically

### ISSUE THREAD

**Issue by anver** [pytesNET/tail.select#39]
I would like to create multiple instances of the component on a click of a button or something like that, is that possible?

**Comment by anver** [comment]
ok I solved my own issue, thx

**Comment by Mehar-Talha-Saleem** [comment]
@anver how did you solved this issue?
Can you please guide me?

**Comment by anver** [comment]
> @anver how did you solved this issue?
> Can you please guide me?

HI Mehar,

I seriously don't remember how I fixed it. Hope you can figure that out.

Thx,
