### ISSUE TITLE
Displaying of tail.select out of viewport

### ISSUE THREAD

**Issue by tomasKucera** [pytesNET/tail.select#4]
When using tail.select, we're getting this issue:
https://screens.zvladnu.cz/1/chrome_2018-10-12_15-14-50.png

The box is shown out of viewport. I prepared an example here:
[tail-select-problem.zip](https://github.com/pytesNET/tail.select/files/2473170/tail-select-problem.zip)

There is a lot of balast but no error in console, so probably it should work.

**Comment by SamBrishes** [comment]
Hello,

Thanks for the report. The current version doesn't calculate the viewport compared to the height of the list itself. It only opens above if there is not enough place below (without to check it this behavior is really a good idea). 

I will fix this as quickly as possible.(At least tomorrow)

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
The Error is fixed in Version 0.4.0. The new Behavior not only checks the available space, it also adapts the height to the respective viewport if needed.

Sincerely,
Sam.

**Comment by jmleighton** [comment]
Hello! I can't find the way to get an array of all selected values.
How can i do it?
Thanks
