### ISSUE TITLE
0.5.7 not showing on Releases

### ISSUE THREAD

**Issue by marcelo-js** [pytesNET/tail.select#40]
Hi, I am unable to update via Bower as there is no 0.5.7 release on Releases.
Could you please update it?

Thanks!

**Comment by SamBrishes** [comment]
Hellow,

thanks for the info, I forgot to publish a respective release here on GitHub (+ the `bower.json` file was also invalid). The problem has been fixed, bower installs now the latest version.

Thanks. 

Sincerely,
Sam.
