### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by elPesecillo** [pytesNET/tail.select#41]
`#### All `
`-   "Todos"`
`### None`
`-   "Ninguno"`
`### Select All`
`-   "Seleccionar todo"`
`### Unselect All`
`-   "Descartar todo"`
`### No Options available`
`-   "No hay opciones disponibles"`
`### No Options found`
`-   "No se encontraron opciones"`
`### You can't select more Options`
`-   "No puedes seleccionar mas opciones"`
`### Select an Option...`
`-   "Selecciona una opción..."`
`### Select up to :limit Options...`
`-   "Selecciona hasta :límite de opciones..."`
`### Type in to search...`
`-   "Escribe dentro para buscar..."`
`### This Field is disabled`
`-   "Este campo esta deshabilitado"`

**Comment by SamBrishes** [comment]
Hellow,

thanks, that's really awesome! Version 0.5.9 already contains your translation.

Sincerely,
Sam.
