### ISSUE TITLE
Translation: it

### ISSUE THREAD

**Issue by albertovincenzi** [pytesNET/tail.select#43]
### All
-   "Tutti"
### None
-   "Nessuno"
### Select All
-   "Seleziona Tutto"
### Unselect All
-   "Deseleziona Tutto"
### No Options available
-   "Nessuna voce disponibile"
### No Options found
-   "Nessuna voce trovata"
### You can't select more Options
-   "Non puoi selezionare più Voci"
### Select an Option...
-   "Seleziona una Voce"
### Select up to :limit Options...
-   "Selezione limitata a :limit Voci..."
### Type in to search...
-   "Digita per cercare"
### This Field is disabled
-   "Questo Campo è disabilitato"

**Comment by SamBrishes** [comment]
Hellow 

Thanks for the translation, that's really awesome. I'll add it as fast as possible. 

Sincerely,
Sam

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait! I just released Version 0.5.10, which contains your translations. Thanks!

Sincerely,
Sam.
