### ISSUE TITLE
Translation: no

### ISSUE THREAD

**Issue by woxvold** [pytesNET/tail.select#45]
### All
-   "Alle"
### None
-   "Ingen"
### Select All
-   "Velg alle"
### Unselect All
-   "Velg ingen"
### No Options available
-   "Ingen valg tilgjengelig"
### No Options found
-   "Ingen valg funnet"
### You can't select more Options
-   "Du kan ikke velge flere"
### Select an Option...
-   "Velg..."
### Select up to :limit Options...
-   "Velg opptil :limit..."
### Type in to search...
-   "Søk..."
### This Field is disabled
-   "Dette feltet er deaktivert"

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your translation, that's really awesome. I'll try to publish your and the new Italian translation tomorrow.

Thanks.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

I just released Version 0.5.10, which contains your translations. Thanks!

Sincerely,
Sam.
