### ISSUE TITLE
Allow HTML inside select options

### ISSUE THREAD

**Issue by markathomas** [pytesNET/tail.select#46]
I have a requirement to show inactive users in read on a per selection basis.  however, with this tool using innerText everywhere I don;t see how this can be accomplished.  Here is an example option:
```
<option value="Some Name">Some Name <span style="color:red;">(Inactive)</span></option>
```

The HTML always get's stripped out

**Comment by SamBrishes** [comment]
Hellow,

the official standard seems [to doesn't allow any HTML inside](https://stackoverflow.com/a/11237834) the `<option>` elements, so the only way to achieve this is to add a custom attribute (which contains an respective indicator if the user is active or not) and use them within the `cbLoopItem` callback, which allows to adapt the rendering of the options.

[I wrote a small demonstration on jsFiddle](https://jsfiddle.net/SamBrishes/3btnaswr/19/)!

Just say we have this HTML structure (Lara Croft is active, Nathan Drake is inactive).
```html
<select>
    <option data-active="true">Lara Croft</option>
    <option data-active="false">Nathan Drake</option>
</select>
```

Then we can use a custom option renderer such as
```javascript
tail.select("select", {
    cbLoopItem: function(item, optgroup, search){
        var li = document.createElement("LI");
            li.className = "dropdown-option"
                         + (item.selected? " selected": "")
                         + (item.disabled? " disabled": "");
        
        // Inner Text
        if(search && search.length > 0 && this.con.searchMarked){
            var rx = new RegExp("(" + search + ")", "i");
            li.innerHTML = item.value.replace(rx, "<mark>$1</mark>");
        } else {
            if(item.option.getAttribute("data-active") === "true"){
                li.innerHTML = item.option.innerText + ' <span class="pin-active"></span>';
            } else {
                li.innerHTML = item.option.innerText + ' <span class="pin-inactive"></span>';
            }
        }

        // Inner Description
        if(this.con.descriptions && item.description){
            li.innerHTML += '<span class="option-description">' + item.description + '</span>';
        }
        return li;
    }
});
```

The styling if up to you of course, my example just contains a respective dot:

![select](https://user-images.githubusercontent.com/31392477/56514295-334f0700-6535-11e9-9a4e-3efce14294d0.PNG)

Sincerely,
Sam.

**Comment by markathomas** [comment]
Perfect! Thanks Sam!
