### ISSUE TITLE
Translation: {tr}

### ISSUE THREAD

**Issue by spritus** [pytesNET/tail.select#48]
### All
-   "Tümü"
### None
-   "Hiçbiri"
### Select All
-   "Tümünü Seç"
### Unselect All
-   "Hiçbirini Seçme"
### No Options available
-   "Seçenek yok"
### No Options found
-   "Seçenek bulunamadı"
### You can't select more Options
-   "Daha fazla Seçenek seçemezsiniz"
### Select an Option...
-   "Bir Seçenek seçin..."
### Select up to :limit Options...
-   "En fazla :limit Seçenek seçin..."
### Type in to search...
-   "Aramak için yazın..."
### This Field is disabled
-   "Bu Alan kullanılamaz"

**Comment by SamBrishes** [comment]
Hellow,

That's really cool. Thanks. I'll publish it together with #47 in the next days.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

a new update has been released. Thanks again for your translation.

Sincerely,
Sam.
