### ISSUE TITLE
Accessible value attribute

### ISSUE THREAD

**Issue by Zenoo** [pytesNET/tail.select#49]
I feel like I'm missing something, but in case of a multiple select, is there an easy way to get the value?

Currently I'm doing `myTail.options.selected.map(o => o.value)` to get a list of the selected options values.

But having an attribute accessible at all time like `myTail.value` would be great.

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue, I'm currently shocked that nobody (not even myself) has noticed this missing feature / function. I (re-) checked the source again, but currently it isn't possible to get direct access to the respective values. D: 

I'll add such a function, of course. Thanks.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
This Issue has been fixed / added & gets released in 0.5.13.

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
