### ISSUE TITLE
cbLoopItem does not check if value exists

### ISSUE THREAD

**Issue by bennymeier** [pytesNET/tail.select#50]
Wie kann ich cbLoopItem nur dann aufrufen, wenn ich es auch brauche? Also bei version === "3"? Ich wäre davon ausgegangen, dass ich cbLoopItem auch einfach undefined returnen lassen kann und dann wird geprüft, ob es das li überhaupt gibt.
````javascript
this.tail = select(this.element, {
            cbComplete() {
                self.initalize();
            },
            cbLoopItem(item) {
                if (self.settings.version === "3") {
                    return self.createIndividualList(item);
                } else {
                    return;
                }
            },
````

Wenn es nicht version 3 ist und nichts machen sollte, kommt in der Konsole:
Cannot read property 'setAttribute' of undefined. Weil nicht geprüft wird, ob li/item überhaupt da ist.

````javascript
`// Create Item
                if((li = (con.cbLoopItem || this.cbItem).call(this, item, ul, search, root)) === null){
                    continue;
                }
                if(li === false){ break; }
                li.setAttribute("data-key", item.key);
                li.setAttribute("data-group", item.group);
                li.addEventListener("click", function(event){
                    if(!this.hasAttribute("data-key")){ return false; }
                    var key = this[g]("data-key"), group = this[g]("data-group") || "#";
                    if(self.options.toggle.call(self.options, key, group)){
                        if(self.con.stayOpen === false && !self.con.multiple){
                            self.close.call(self, self.con.animate);
                        }
                    }
                });
````

Gibt es vielleicht einen anderen Weg? Ich kann in dem Objekt select(el, {
   cbLoopItem(item) // condition?
}); keine Kondition benutzen, Das wollte ich dann in cbLoopItem machen.

**Comment by SamBrishes** [comment]
Hallo,

die Callback Funktion `cbLoopItem` erlaubt (ausschließlich) 3 Rückgabewerte:

- `null` um die aktuelle Option zu überspringen (Skip Item, Continue)
- `false` um den gesamten Render-Prozess zu beenden (Break Loop)
- das entsprechende Element welches gerendert werden soll

Es wird nicht geprüft ob der rückkehrende Wert ein gültiges Element ist oder nicht, sondern es wird explizit angenommen, sofern es nicht `null` oder `false` ist.

### Beispiele (Theorie)
Also rein theoretisch lässt sich damit folgendes Konstrukt bilden:

```javascript
tail.select("select", {
    cbLoopItem: function(item, ul, search, root){
        if( isValidOption( item ) ){
            return renderOption( item );
        }
        if( breakWalk( item ) ){
            return false;   // Beendet den gesamten Render-Prozess
        }
        return null;        // Überspringt lediglich die Option
    }
});
```

### Beispiele (Praxis)
Ein praktisches Beispiel findest du auf [jsFiddle](https://jsfiddle.net/SamBrishes/ua6efjp8/4/): Dort werden ausschließlich die Optionen gerendert die mit einer Zahl im Wert enden. Das ist natürlich eine einfache Grundlage, allerdings stellt es gut zur Schau, dass Optionen die nicht gelistet werden dennoch selektiert werden (können).

```javascript
tail.select("select", {
    cbLoopItem: function(item, ul, search, root){
        var last = item.value[item.value.length - 1];
        if(isNaN(parseInt(last))){
            return null;
        }
        return this.cbItem(item, ul, search, root);
    }
});
```

### Beispiel
Ich kenne jetzt deinen Code nicht, aber wenn ich das richtig verstanden habe, möchtest du solange den "Standard Renderer" verwenden, bis `self.settings.version === "3"` ist? Wenn ja, sollte der untere Code funktionieren denn `this.cbItem()` ruft die Standard-Methode zur Erstellung der Optionen auf.

```javascript
select(this.element, {
    cbComplete: function(){
        self.initalize();
    },
    cbLoopItem: function(item, ul, search, root){
        if(self.settings.version === "3"){
            return self.createIndividualList(item);
        }
        return this.cbItem(item, ul, search, root);
    }
});
```

Sincerely,
Sam.
