### ISSUE TITLE
Adding a selected option

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#52]
Looks like version 0.5.0 broke that (with changes in the function `set` I guess).

You still can add options, but you can't sets them as selected. But maybe I missed something.

[here's a jsfiddle](https://jsfiddle.net/Calak/05zq4mga/)

**Comment by SamBrishes** [comment]
Hellow,

thanks for this bug report and for the jsFiddle. I'll check / fix that as fast as possible.

Sincerely,
Sam.

**Comment by Calak** [comment]
So, I investigated this issue, and there is some good and bad.

With ```this.option.add()``` in his post-5.0.0 version (passing an object), all seems to work fine, maybe just add the possibility to postpone view refreshing until wanted **(1)**.

With ```this.option.add()``` is his pre-5.0.0 version (multi parameters), the options are indeed added behind in the background, but the view is not refreshed if we don't give the rebuild parameter (seems logic). 

But using the long form and passing "rebuild" to ```true``` to force the refresh causes a ```TypeError``` exception to be threw.
To fix that, we can change, in the last line of the ```set()``` function, the call ```this.self.callback(this[this.length-1], "rebuild")``` into a pre-5.0.0 version ```this.self.callback(this.items[grp][key], "rebuild")``` **(2)**. 

Until this bug is fixed, as a workaround, don't set rebuild parameter and calls ```this.query()``` after ```this.option.add()``` to refresh the view (this work, but I'm feeling that this name is unintuitive in this context **(3)**).

With single-select, if there is already an option selected (and it's always the case if the deselect's setting isn't set), the added one, isn't selected. We have to call ```this.options.select('KEY', 'GROUP');``` after adding, to force the selection manually. IMHO, the intuitive way is that, in single-select, if we add selected options, the last one added should be the one selected. **(4)**

So, yeah, we can add selected options, but the way to do hurts a bit. 

I understand that many of these points are due to design decisions (except the `` TypeError``` exception, I guess... :)), but it would be nice if we can debate about it.

**Comment by twizzlerz04** [comment]
Still fixing?

**Comment by SamBrishes** [comment]
I guess #64 should be already the fix, just need to be implemented.

**Comment by Calak** [comment]
@SamBrishes in my fork, I did a "merged" branch, with all PR together  (if you want to test it or/and can't auto merge because of *.min.js files)

**Comment by SamBrishes** [comment]
Hellow @Calak,

I definitely agree with you and thanks for your help. I would really appreciate your code / work, but don't stress you out with your deadline, I couldn't merge / check it before Saturday anyway. :D 

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
