### ISSUE TITLE
Allow minimal search length

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#57]
I think that a good idea would be to give users the ability to setting up the minimal search length instead of hardcoding it.

It's damnly trivial to implements and add a plus value to it 
Personally, my preference go for "at least 2 char" instead of 3. Some poeple could want a "live" filtering, with 1 as minimal length.

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your request. That's true and should be implemented.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
