### ISSUE TITLE
Search input, escaping, regex vs texual

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#59]
As talked in issue #53, backslashes are treated as escaping char.

The fix would be trivial (doubling backslashes for the search  parameters in ```cbItem()``` and in ```find()```) be I'm not sure that's the right way to do.

In fact, the search itself is not textual but a RegEx matcher (By the way, is it a bug or an undocumented feature?)

Although I think a RegEx matcher can be a powerful tool in a search field, if the user is not aware, it can lead to some misunderstandings (imagine he wants to look for options containing ellipsys)

There are some possible solutions:
1. Leave it like this, just by documenting it
2. Replace the search with a text search, escaping the original RegEx search.
3. Combine both, leaving the user a choice of which method, for example using a `searchRegex: true` parameter.

What do you think about it?

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
