### ISSUE TITLE
Ignoring selected attribute

### ISSUE THREAD

**Issue by tomasKucera** [pytesNET/tail.select#6]
I found an issue shown in example here: https://codepen.io/tomdux/pen/ReLBXK?editors=1000

The select box has an option with "selected" attribute but the tail.select doesn't show the selected option as chosen in default state after pageload.

**Comment by SamBrishes** [comment]
Oops, I merged the `init()` and `set()` method within the `tailOptions` class and this may breaked the `.selected` attribute check.

I fixed this issue in Version 0.4.1, thanks for reporting!
