### ISSUE TITLE
Find() function branching and the "any" parameter

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#61]
I am working on issue #59 to make a proposal, and I am wondering about the `"any"`parameter of the `find()` function.

Can you give an example of a use case that uses it? If I inspect your code, this is the only place where you deal with it. I know that's for search also into the element's attributes, but you do not give any way to do it (tell me if I'm wrong). So, did I miss something, or is it a dead code introduced in version 0.5.0?

---

Anyway, I think that function's branching can also be optimized

        find: function(search, config){
            var regex = new RegExp(search, "im"), filtered = [], self = this,
                filterKey = function(opt){ return regex.test(opt.text || opt.value); },
                filterAny = function(opt){ return (filterKey(opt.text) || Array.apply(null, opt.attributes).filter(filterKey).length > 0); },
                filter = (config == "any") ? filterAny : filterKey;
            
            if (!self.self.con.searchDisabled) filter = function(opt) { return self.disabled.indexOf(option) == -1 && filter(opt); }

            Array.apply(null, this.self.e.options).map(function(opt){
                if(filter(opt)){ filtered.push(self.get(opt)); }
            });
            return filtered;
        },

Should I do a separate PR for this, or could I included it in the PR for the proposal about #59 (or maybe you'll just rejects this refactoring)

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
