### ISSUE TITLE
Apostrophes inside initially disabled/selected options 

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#62]
`callback()` is throwing a `DOMException: Can not execute 'querySelector' on 'Element'` when calling `tail.select` on a `<select>` 
that contains some `<option>` with the attributes `selected` or `disabled` sets and apostrophes inside the inner text.

https://jsfiddle.net/jc0sheau/

Related to #53 and also fixed by #55

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
