### ISSUE TITLE
UP-arrow when last option is disabled

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#66]
[Here's a subtle bug.](https://jsfiddle.net/Calak/L9f2hsex/)

If your last option is disabled, using "up-arrow" key from the first element don't set focus on the before-last, or more generaly, the last not-disable one.

To fix that, you should replace:

                 } else if(!opt && key == 38){
                    opt = self.dropdown.querySelector("ul:last-child li:not(.disabled):last-child");
                }
   
by:

                 } else if(!opt && key == 38){
                    var tmp = document.querySelectorAll(".dropdown-option:not(.disabled)");
                    opt = tmp[tmp.length - 1];
                }

**Comment by SamBrishes** [comment]
Hellow,

thanks for finding the next bug :D 

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
