### ISSUE TITLE
hidden option shouldn't be displayed

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#67]
A common usage is to set an hidden-disabled-selected option with empty value, to use as a placeholder.

https://jsfiddle.net/Calak/qchstpj7/

IMHO, when you parse the base options, you should omit `hidden` options.
You could event, in case no placeholder are provided, get the placeholder value from this hidden-disabled-selected-empty option.

As a bonus, you could also handle the `required` attribute on the `<select>` itself.

**Comment by SamBrishes** [comment]
Hellow again,

thanks for showing me the `hidden` attribute, never heard about that... But according to the official W3C standard [this is also "really" new](https://www.w3.org/TR/html51/editing.html#the-hidden-attribute)... So 2017. :D 

I'll check it out.

Sincerely,
Sam.

**Comment by Calak** [comment]
Yes, the "old" method was to hide the placeholder in the list with css (which we could also detect)

**Comment by SamBrishes** [comment]
The hidden options has been added in 0.5.15, the `required` attribute will be added in 1.0.0.

**Comment by Calak** [comment]
Fine. I'll check it when I'll be back

**Comment by SamBrishes** [comment]
Done, will be published in 0.6.0.
