### ISSUE TITLE
New All / None Buttons

### ISSUE THREAD

**Issue by SamBrishes** [pytesNET/tail.select#68]
Hellow,

since I've already written the code demonstrate below, I will implement the new "All" / "None" buttons directly in 0.5.13. This means that the "Select All" and "Select None" buttons gets renamed into "All" and "None" too and moved, that it will overlay the search field. The respective translations gets removed completely. The optgroup-specfic "All" / "None" action buttons gets hidden until the cursor (mouse cursor, or arrow keys) is within the respective group.

I'm currently not sure if I will implement the new (and shown) Icon Font (Feather Icons) too directly, or in version 1.0.0.

The demonstration GIF:
![tail-select](https://user-images.githubusercontent.com/31392477/51388396-92ae0d00-1b29-11e9-9f9b-52760069e3c5.gif)

Sincerely,
Sam.

_Originally posted by @SamBrishes in https://github.com/pytesNET/tail.select/issues/29#issuecomment-455539464_

**Comment by Calak** [comment]
It's awesome!  I would also appreciate if you implement the new icon set!

Another thing I'd like to see and that would open up countless possibilities would be to provide (via config) callbacks to make the label and the search field as you did for a group / element.

A can post an issue if you want.

**Comment by SamBrishes** [comment]
The new icon set was used in 0.1.0 - 0.3.0, I switched in 0.3.0 to the Octicons.

I already wrote an action / plugin hook system for version 1.0.0, which at least allows hooking in all functions called in the `.update()` method (`.updateLabel()`, `.updateContainer()`, `.updatePin()` and `.updateCSV()`) + `.init()` / `.remove()` / `.reload()`.  So it is already planned :D

**Comment by SamBrishes** [comment]
Hellow,

This has been fixed / added in Version 0.5.13. Thanks.

Sincerely,
Sam.
