### ISSUE TITLE
[1.0.0][Plugin] Tag Input

### ISSUE THREAD

**Issue by SamBrishes** [pytesNET/tail.select#71]
Hellow,

instead of collecting all 1.0.0 requested and changes on [one single issue](https://github.com/pytesNET/tail.select/issues/30) I decided to split them into single issues for a better discussion and a better develop-process in general.

### Tag Input
one of the planned plugins for version 1.0.0 is the tag-input function, known from selectize.js. It allows creating new options / items - using the search field - if they don't exist yet. This would increase the usability and capability significantly, still be optional because it isn't required on every page.

Sincerely,
Sam.

**Comment by Calak** [comment]
The whole concept of `MultiContainer` should be moved to this plugin too, keeping main source smaller

**Comment by SamBrishes** [comment]
Done, will be published within the "select-input" plugin in 0.6.0.
