### ISSUE TITLE
Less styles, more issues :)

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#74]
With your last update, no more .hover classes working. It seems that you forget about it in your ".less" files, unless you just drop it (but I guess not)

On *defaut* and *modern* themes, when you have many nearby selects , they overlap a bit: Setting the `margin` to 1px on `.tail-select` fixes it.

Again on *default* and *modern* themes, the dropdown is displayed behind other selects. Changing the  `z-index` of `.select-dropdown` fixes that.

NB: Coming PR soon ;)

**Comment by SamBrishes** [comment]
Thanks, has been merged :D
