### ISSUE TITLE
Separating files

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#76]
Maybe it would be a huge improvement to separate handwritten files from generated ones.

For example:

    dist/
        css/*
        js/* 
            langs/* 
    src/
        less/*
        js/*
        langs/*

So, we have, in details:

- **_dist/css/*_**
  - All CSS files generated from _.less_
  - All minified CSS files.
- **_dist/js/lang/*_**: 
  - All indivual translation files copied
  - _tail.select-all.js_ generated from individual translation
  - All of these translation files minified
- **_dist/js/*_**
  - _tail-select.js_ & _tail-select-es6.js_ copied
  - _tail-select-full.js_ generated from _tail.select.js_ and _langs/tail.select-all.js_
  - All of these files minified

- **_src/less/*_**
  - All _.less_ files
- **_src/js/*_**
  - _tail-select.js_
  - _tail-select-es6.js_
- **_src/langs/*_**
  - All individual translation files
- **_src/*_**
  - A build script, as for the one you did for compile _.less_, but that will also do the job for _js_ and _langs_ directories.

So, when you work on the code, we dont have to worry anymore about minified js files, _tail-select-full.js_, etc.

What do you think about that?
I'm pretty sure you plan this for the v1.0.0, but is there any chance we get it earlier?

Sincerely

**Comment by SamBrishes** [comment]
Hellow,

thanks for the suggestion, and as you already mentioned... Yes, this is planned for version 1.0.0 (as shown below). I'll check if it can be done earlier.

![dir](https://user-images.githubusercontent.com/31392477/60848034-4b096380-a1e5-11e9-81c4-fb952c7a2125.PNG)

Sincerely,
Sam.

**Comment by Calak** [comment]
So, I close and let you re-open if you can do it earlier :)
