### ISSUE TITLE
0.5.14 .min.js is empty

### ISSUE THREAD

**Issue by Zenoo** [pytesNET/tail.select#77]
Every `.min.js` file in the 0.5.14 release is empty.

**Comment by SamBrishes** [comment]
Hellow,

thanks for this information. Version 0.5.x gets compiled manually using jscompress, so I guess I missed that. The current [master branch](https://github.com/pytesNET/tail.select/zipball/master) contains now the minifed versions again, a small HotFix to npm will be released soon.

Sincerely,
Sam.

**Comment by Calak** [comment]
Just when I asked you if we can put an automation script.

Coincidence? I guess not!

:)

**Comment by Zenoo** [comment]
Just a heads up, if it can help :

I usually use a `preversion` script in my `package.json` to make sure everything is set as I want it to be in the packages that need minification/obfuscation.
That way you don't have to think about it, it'll trigger before updating the version using `npm version patch/minor/major` & cancel the version if something goes wrong.

**Comment by SamBrishes** [comment]
@Calak The automation script will come... In Version 1.0.0 ;)

@Zenoo Thanks, sounds interesting, I'll check it out :D

**Comment by SamBrishes** [comment]
Has been fixed in 0.5.15.

Thanks!
