### ISSUE TITLE
Differentiate .disabled and .hover

### ISSUE THREAD

**Issue by Calak** [pytesNET/tail.select#79]
One of the most frustrating things with the default style, is the lack of visual difference between hovered and disabled options.
There's only the leading icon and the cursor.

Okay, that's not totally true, .disabled options have their texts striked, but IMHO, this is unsightly.

So, I tried to fix that, setting a color based on @primary for hovered options, and a greyscaled lighten for disabled ones.
For disabled options' text, instead of having a line through, i engraved it.

I also added a transition property, to change background smoothly.

![captured (1)](https://user-images.githubusercontent.com/410375/60880842-bb939d00-a244-11e9-8be7-bdc7fdf714ab.gif)
![captured (2)](https://user-images.githubusercontent.com/410375/60880849-bfbfba80-a244-11e9-80a4-547ab9317595.gif)

What is your opinion or feeling?

Sincerely.

**Comment by SamBrishes** [comment]
Hellow,

awesome! Can you turn this into a PR, please? :D 

I missed the minified JavaScript files in 0.5.14, so I want to publish a small HotFix (0.5.15) today to npm and bower. This can be directly a part of the small update.

Thanks for your work.

Sincerely,
Sam.

**Comment by Calak** [comment]
Sure!

I edit the others themes in the same way and I submit a PR

**Comment by SamBrishes** [comment]
Has been added in 0.5.15.

Thanks!
