### ISSUE TITLE
How can i select a item from tailselect by ajax

### ISSUE THREAD

**Issue by antoniogonzalez7732** [pytesNET/tail.select#83]
I need to select dinamically item from select "Tailselect".

it is that posible? 

how can i do that?

I have a select and I need 4 options.

when selecting the option all, I need that the rest of the items are automatically deselected, if I select the three remaining elements equally the option must all be selected automatically and the rest must be deselected.

**Comment by SamBrishes** [comment]
Hellow,

I'm not really sure if I understand your request correctly, but if yes the following script should solve your issue, [as shown on this jsfiddle.net](https://jsfiddle.net/SamBrishes/5bc6y8pa/38/).

![selector](https://user-images.githubusercontent.com/31392477/61569044-cb518380-aa85-11e9-882a-95d5c93eb9b3.gif)

The following script 
- selects the "All Options" item, if the user selects all available options
- unselects the "All Options" item, if the user just selects a single option

```javascript
tail.select("select", {
	stayOpen: true
}).on("change", function(opt){
    var selected = this.options.selected;
    
    if((opt.key === "all" && opt.selected) || (selected.length === this.options.length - 1)){
        this.options.all("unselect");
        this.options.handle("select", "all", "#", true);
    } else {
    	if(this.options.is("selected", "all", "#")){
            this.options.handle("unselect", "all", "#", true);
        }
    }
    
    this.query();
});
```

Sincerely,
Sam.

**Comment by antoniogonzalez7732** [comment]
Thanks, this is great, where there are more examples of this plugin

**Comment by antoniogonzalez7732** [comment]
for example, how can I change the name of the labels at run time or close the option select when the focus is lost? I'm an amateur programmer, thanks for all your help.

**Comment by SamBrishes** [comment]
Hellow,

there is currently no list or collection for such explicit programming examples. I just have the [demonstration page](https://github.pytes.net/tail.select/), which shows many examples without writing (much own) code. 

But [here is a list](https://github.com/pytesNET/tail.select/wiki/Public-Methods) with all available public methods, which each single `tail.select` instance offers you. The following code allows you to "change" the label during the runtime, of course, you need to adapt this to your own, productive website (but here is a small [example on this jsfiddle](https://jsfiddle.net/SamBrishes/0mzc4de1/13/)):

```javascript
// Init tail.select
let select = tail.select("select");

// Get Option using the option value and '#' as option group
let option = select.options.get("option-a", "#");

// Change Value and innerText of the option
option.value = option.option.innerText = "Option A (Main)";

// ReBuild
select.query();
```

And for your second example: You can use `select.close()` to close the dropdown container everywhere, combine this with the `blur` event of the main select container (available under `select.select`) and you will receive the following (which is also available on the jsfiddle example above.):

```javascript
select.select.addEventListener("blur", function(){
	select.close();
});
```

Sincerely,
Sam.

**Comment by antoniogonzalez7732** [comment]
Thanks for the help. You do an excellent job.

Thank you very much for sharing
