### ISSUE TITLE
Selector or filter select

### ISSUE THREAD

**Issue by venkatdev22** [pytesNET/tail.select#85]
Is there option to specify filter in the selector while constructing drop down like below ? I want to do it without jquery.
  tail.select(".multiple:last-child", { search: true, multiSelectAll: true, placeholder: "Select options" });

**Comment by SamBrishes** [comment]
Hellow,

you can use all available vanilla CSS selectors (check out the [CSS Selectors Reference](https://www.w3schools.com/cssref/css_selectors.asp) on w3schools.com for some examples). 

Depending on your HTML structure you can either use ...

```javascript
tail.select("select:last-of-type", { });
```

or using `:last-child` by defining at least on "parent" element / container ([as shown on this example](https://jsfiddle.net/SamBrishes/q8Ln93kh/3/)), but note that the `<select>` element must be the LAST children of the respective parent ...

```javascirpt
tail.select("div.selectors select:last-child", { });
```

```html
<div class="selectors">
    <select> </select>

    <select> </select>

    <select> </select>
</div>
```

Sincerely,
Sam.

**Comment by venkatdev22** [comment]
Sam,
Thanks for the quick response ! I have another question, will open separate ticket.

**Comment by Calak** [comment]
@venkatdev22 a nicer option would be to add a classname to select you want to replace and so, the selector could be more scalable.

**Comment by SamBrishes** [comment]
That's true. An additional classname or an ID or what ever is always better, there are many ways to handle this, as shown in the CSS Selector Reference. :D
