### ISSUE TITLE
SearchConfig usage

### ISSUE THREAD

**Issue by venkatdev22** [pytesNET/tail.select#86]
Can I have usage example for SearchConfig specified in https://github.com/pytesNET/tail.select/wiki/Public-Options#searchConfig.
I am trying to configure search based on options attributes(Not using "text, "value"). 

I have requirement to perform search on hidden(not visible) value mapped to each option. 
Currently, different multi-select plugin doing a ajax call back and binding data to select on search every key up event backed by Get-API . 

If there is a way to make search on attribute, In page load itself I will bind a search text of each option as an attribute. I can avoid ajax call.  If ajax is avoidable, please let me know how can I attach an key press event listener to a multi-select control search text box.

**Comment by venkatdev22** [comment]
Also please let me know if there is option to limit search response options

**Comment by venkatdev22** [comment]
Found a way to set search options based on option attribute. Used below code.

 var ulmLastMultiple = tail.select(".ulmLastMultiple", {
         search: true, searchConfig: [             
          "text", "attributes"
        ], multiSelectAll: true, placeholder: "Select options"
    });

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait, I was really busy.

Thanks for sharing the solution!

Sincerely,
Sam.

**Comment by Calak** [comment]
Yeah, you found the way yourself :)
But, if you want to restrict to some attributes, you have to provide a custom function matcher as searchConfig
