### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by elPesecillo** [pytesNET/tail.select#9]
Hello,

I am trying to get all the elements selected after the user select some items and close the dropdown component, but I am not able to find how to bind an event to listen when the user collapse the dropdown, so my question is. there is an easy way to handle that or are you planning to add some custom events to the component?. 
Also I think that some public methods would be very helpful,  i.e. get all the elements selected, change the values selected, etc.

**Comment by SamBrishes** [comment]
Hello,

I'm really sorry for the long wait, I was really busy at work. 

I'm not finished yet with the documentation, but there are two ways to bind methods to the **tail.select** instance and some public methods are already available. The future versions may contain more specific event listeners, but I plan to include a `selectAll`, `unselectAll` and `invertSelection` methods at least.

## Event Listener
You can use `.on()` - one of the public methods offered by the **tail.select** instance - or `addEventListener` on the main container of the **tail.select** instance (accessable through `tailSelect.select`).

I wrote a small example ([jsFiddle](https://jsfiddle.net/qkdr2emw/1/))

```javascript
document.addEventListener("DOMContentLoaded", function(){
    var SelectField = tail.select("select");
    
    /*
     |  The internal Event Listener
     |  Use `this` to access the tail.select class
     */
    SelectField.on("close", function(){
        var html = "";
        for(var l = this.options.selected.length, i = 0; i < l; i++){
            html += this.options.selected[i].text + "<br />";
        }
        document.querySelector("#result1").innerHTML = html;
    });
    
    /*
     |  The JavaScript own Event Listener
     |  Use the `event.detail.self` object to access the tail.select class
     */
    SelectField.select.addEventListener("tail.select::close", function(event){
        var args = event.detail.args,
            self = event.detail.self;
    
        var html = "";
        for(var l = self.options.selected.length, i = 0; i < l; i++){
            html += self.options.selected[i].text + "<br />";
        }
        document.querySelector("#result2").innerHTML = html;
    });
});
```
The options handling is done by `tailOptions`, which instance is assigned to `tailSelect.options`. The `tailOptions` prototype has the following properties:

```
    tailOptions.length         // Number of all Items
    tailOptions.selected       // Array with all selected `<option>` elements
    tailOptions.disabled       // Array with all disabled `<option>` elements
    tailOptions.items          // All Items `ordered` with there group
    tailOptions.groups         // All Groups, except the `#`/`ungrouped` Group
```

### Event Types
The current version of the **tail.select** script supports this 3 events:

| .on()     | .addEventListener()   |                                          |
| --------- | --------------------- | ---------------------------------------- |
| open      | tail.select::open     | Triggers when the dropdown field opens.  |
| close     | tail.select::close    | Triggers when the dropdown field closes. |
| change    | tail.select::change   | Triggers on every change (select, unselect, enable, disable) |

## Public Methods
The curent version offers the following public methods:

### .choose(state, key, group)
This method changes the state of a single option.

#### state
"select", "unselect", "enable", "disable" depending on the desired action

#### key
The `<option>` key,  which is either `value` or the inner option text (if no `value` attribute is available!)

#### group
The `<optgroup>` label of the option or null (`#` respectivly) if the option has no optgroup!

### .open()
This method just opens the select field.

### .close()
This method just closes the select field.

### .toggle()
This method opens / closes the select field.

### .remove()
This method removes the tail.select instance.

### .reload()
This method re-builds the tail.select instance.

### .config(key, value)
This method returns or sets a configuration option. **IMPORTANT** When changing some specific options you MUST call `reload()` to take an effect.

#### key
The option key to either get the value (if no second parameter is passed) or to change the respective value (pass an second parameter).

#### value
The option value to overwrite the existing one.

### .on(event, callback, args)
The internal event listener (see above)
<br />
-----------------------
<br />
I hope I could answer your question


Sincerely,
Sam.

**Comment by elPesecillo** [comment]
Thank you, works like a charm.

**Comment by SamBrishes** [comment]
Perfect.
I will leave this issue open, until the documentation on GitHubs Wiki Pages is finished.

**Comment by SamBrishes** [comment]
The [GitHub Wiki](https://github.com/pytesNET/tail.select/wiki) has been updated and contains now MANY tail.select related informations and descriptions.

I will close this issue for now.
