### ISSUE TITLE
[Core] - Merge Callback options with Event Listener

### ISSUE THREAD

**Issue by SamBrishes** [pytesNET/tail.select#91]
Hellow, again, ...

After writing the most functions in the new Options class, I'm planing the new callback system. I want to remove the `cb*` options and use some additional names on the `.on()` method. The current code looks like this:

```typescript
/*
 |  PUBLIC :: LISTENER
 |  @since  1.0.0
 |  
 |  @param  multi   A single event or callback name as STRING, multiple as ARRAY.
 |                  :: AVAILABLE EVENTS ::
 |                  Events just gets triggers to inform custom functions and methods.
 |                      "open"          When the dropdown gets open.
 |                      "close"         When the dropdown gets closed.
 |                      "change"        When one or more <option> states gets changed.
 |                      "selected"      When one or more <option>s gets (un)selected.
 |                      "disabled"      When one or more <option>s gets (en|dis)abled.
 |                      "hidden"        When one or more <option>s gets hidden | shown.
 |                      "update"        When the update method gets called.
 |                      "remove"        When the remove method gets called.
 |                      "reload"        When the reload method gets called.
 |
 |                  :: AVAILABLE CALLBACKS ::
 |                  Callbacks can manipulate the internal flow and may require a returning value.
 |                      "empty"         When the dropdown is queried empty.
 |                      "query"         When a query gets parsed / calculated.
 |                      "search"        When a search query gets parsed / calculated.
 |                      "loop:start"    When the dropdown rendering starts.
 |                      "loop:item"     When a dropdown <option> gets rendered.
 |                      "loop:group"    When a dropdown <optgroup> gets rendered.
 |                      "loop:end"      When the dropdown rendering ends.
 |  @param  func    A callback function.
 |  @param  array   Some additional arguments, which should get passed in the callback function.
 |
 |  @return this    The tail.select instance.
 */
on(event: string | Array<string>, func: Function, args: Array<any>) {
    event = (typeof event === "string")? [event]: event;
    for(let ev in event) {
        if(!(ev in this.callbacks)) {
            this.callbacks[ev] = [];
        }
        this.callbacks[ev].push({ callback: func, args: (args instanceof Array)? args: [] });
    }
    return this;
},
```

Instead of using `cbEmpty: function(){ }` you can now use `.on("empty", function(){ })`, the same happens on `cbLoopItem` (alias `.on("loop:item")`) and `cbLoopGroup`  (alias `.on("loop:group")`). Just the `cbComplete` callback gets removed, because it isn't really necessary (you can also just write your completion code after the `tail.select` initialization).

The `change`, `selected` and `disabled` events triggers now just once, when clicking on an All / None Button and gets called with an respective object containing all "changed" options.

### Small Hack
You may think "This could be problematic if the hook can not be added until after initialization.". And yes, that is true, at least if you enable the `startOpen` option. In this case, I'm testing and playing with a small workaround consisting of a small timeout:

```typescript
if(this.con.startOpen) {
    (function(self){ setTimeout(function(){ self.open(self.con.animate); }, 150); }(this));
}
```

Sincerely,
Sam.

**Comment by Calak** [comment]
You could also maybe drop the startOpen option, and let the user relying on a "initialized" event to open the dropdown by himself, no?

**Comment by Calak** [comment]
Also, having multiples select, opened on start, can brings some problems if we close dropdown when he lose focus or when users click outside (incoming with my PR).
That can be fixed with more code to check if the control was previously focussed before closing it, but IMHO it's not clean. 

What do you think about that?

Sincerely

**Comment by Calak** [comment]
Also, having multiples select, opened on start, can brings some problems if we close dropdown when he lose focus or when users click outside (incoming with my PR).
That can be fixed with more code to check if the control was previously focussed before closing it, but IMHO it's not clean. 

What do you think about that?

Sincerely

**Comment by SamBrishes** [comment]
I guess that's true, drop that, the user can open it itself with just a single line of additional code. This may prevents errors on multiple `<select>` selectors, which doesn't have the `stayOpen` option enabled.

> or when users click outside (incoming with my PR)

Clicking outside the dropdown field already closes the dropdown field (its the [second event listener on the `.bind()` method](https://github.com/pytesNET/tail.select/blob/master/js/tail.select.js#L434)) or what do you mean?

**Comment by Calak** [comment]
In v0.5.14 at least on chrome, it doesn't. I'm currently not at home, so I can't prove it. 
Maybe sunday or next week.

**Comment by SamBrishes** [comment]
This has been done in the upcoming release 0.6.0
