### ISSUE TITLE
tail.select(config); not working on IE?

### ISSUE THREAD

**Issue by twizzlerz04** [pytesNET/tail.select#92]
This code is not working on IE, it doesn't load the search, deselect and classnames.

`
tail.select('select[name="form-id"]', {  
            search: true, 
            deselect: true,  
            classNames: true,
        });  
`

While on chrome and firefox its working fine. What seems to be the problem here?

**Comment by Calak** [comment]
- Which version of IE?
- What's your result? A default-initialized `tail.select` object?
- Did you have some message in the developer console? (F12 I think on IE)

**Comment by twizzlerz04** [comment]
Version 11.
It only loads default tail.select.
And here is the result on the console
![image](https://user-images.githubusercontent.com/37446247/61856643-1e4b9080-aef5-11e9-9e61-7e5d8d9a7c91.png)

**Comment by twizzlerz04** [comment]
> Version 11.
> It only loads default tail.select.
> And here is the result on the console
> ![image](https://user-images.githubusercontent.com/37446247/61856643-1e4b9080-aef5-11e9-9e61-7e5d8d9a7c91.png)

by the way I console log this part to check it
![image](https://user-images.githubusercontent.com/37446247/61856811-784c5600-aef5-11e9-97f9-07d953f61a96.png)

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue. IE11 recognize `Object.constructor();` (as used in the `clone()` helper method) as a function and not as an object (as the common browsers).

I tested it by changing [line 105](https://github.com/pytesNET/tail.select/blob/master/js/tail.select.js#L105) from
```javascript
config = (typeof config === "object")? config: {};
``` 

to

```javascript
config = (config instanceof Object)? config: {};
```

and tada... it works.

I'll check the other use of the `clone()` function and upload a small fix for this.

Sincerely,
Sam.

**Comment by twizzlerz04** [comment]
It works fine now. Thank you again my lords.
