### ISSUE TITLE
Select function only works with optgroup

### ISSUE THREAD

**Issue by ederrf** [pytesNET/tail.select#93]
Hi guys, first of all, thanks for the component, tail.select is pretty good!

I am having a problem with the select function (https://github.com/pytesNET/tail.select/wiki/public-methods#selectkey-group): when I use it on a select that has optgroup it works but it doesn't with a select that  #does not use optgroup.

I've simulated the situation here: https://jsfiddle.net/ederribeiro/j0xu491y/21/

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue, I'm glad that you like the component. :D

The current version requires you to pass `#` as group for ungrouped options. I [forked your jsfiddle](https://jsfiddle.net/SamBrishes/rhgvs90y/3/) added the `'#'` as group and changed the second listener from `select1` to `select2` (I suppose this was a small mistake).

Sincerely,
Sam.

**Comment by ederrf** [comment]
Thanks @SamBrishes ! That works!

**Comment by SamBrishes** [comment]
No Problem, I'm glad that I could help you.

And thanks for the coffee :D
