### ISSUE TITLE
Dependent/Cascading Dropdown Select in Datatables with tail.select

### ISSUE THREAD

**Issue by minhnguyen1406** [pytesNET/tail.select#95]
Hi there,

I have a table from DataTables with sort and filter. I know how to make the select filters dropdown dependent on each other without using tail.select. It means that when you select one option from one select filter, it gets updated and when you continue to filter with another filter select, they'll show the options accordingly in their column. This [example](https://jsfiddle.net/94tL6f1m/) will demonstrate what I need more clearly. 

However, I could not do that with tail.select applied. All of the options are still there when one of the select filter gets updated. Is there any ways to do that in tail.select? Thank you!

**Comment by Calak** [comment]
With tail.select, does source's select are updated ( you need to inspect the page)? Did you tried to call .reload() on tail's objects?

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue, [try this jsfiddle](https://jsfiddle.net/SamBrishes/fegx74uk/15/). It should work, I changed the `<select>` JavaScript parts into

```javascript
$(document).ready(function() {
    var table = $('#example').DataTable({
        initComplete: function() {
            this.api().columns().every(function() {
                var column = this;
                var select = $('<select class ="filter"></select>')
                             .appendTo($(column.footer()).empty())
                             .tailselect({ deselect: true, width: 225 });
                             
                select.on("change", function(){
                    var val = $.fn.dataTable.util.escapeRegex(this.value());
                    column.search(val? ('^' + val + '$'): '', true, false).draw();
                });
                
                column.data().unique().sort().each(function(d, j) {
                    select.options.add(d, d, '#');
                });
                select.query(); // Reload Dropdown Query after option has been added
            });
        }
    });
    table.on('draw', function() {
        table.columns().indexes().each(function(idx) {
            var select = $(table.column(idx).footer()).find('select').tailselect();

            if (select.value() === null) {
                select.reload(); // Clear Dropdown
                
                table.column(idx, {
                    search: 'applied'
                }).data().unique().sort().each(function(d, j) {
                    select.options.add(d, d);
                });

                select.query(); // Reload Query
            }
        });
    });
});
```

Sincerely,
Sam.

**Comment by minhnguyen1406** [comment]
Thank @SamBrishes and @Calak for the suggestions and answers. It works like a charm. I have another question : how can I apply the same thing but with multiple selections in tail.select. Once again, thank you, I really appreciate it.

**Comment by minhnguyen1406** [comment]
Hi @SamBrishes and @Calak, can you guys help me apply the same thing for muliple selections in tail.select. I've tried and haven't figured out it yet. Thank you!

**Comment by Calak** [comment]
@minhnguyen1406  You mean, like that: https://jsfiddle.net/Calak/ajuxqe9r/ ?

;)

**Comment by minhnguyen1406** [comment]
Thank you, it works beautifully! Keep up the good work, guys, I really appreciate it!
