### ISSUE TITLE
Accents issue

### ISSUE THREAD

**Issue by vjmartins** [pytesNET/tail.select#97]
Hi.

First, sorry my English..
Second, i found your work today and its awesome. 

It´s possible to search word with accents automatically.

Something like that:
I search for **Sonia** and results include **Sonia** and **Sónia**.

Thanks

**Comment by SamBrishes** [comment]
Hellow,

thaks for your issue. I'm glad that you like our work. :D

This part has been re-written by @Calak and is called "linguisticRules", which is an own option. It has a view default values, but `ó` isn't one of them. Check out [this CodePen](https://codepen.io/sambrishes/pen/vombzN), it shows how you can configure the tail.select instance to see `ó` as `o` (when searching). The config:

```javascript
tail.select("select", {
    search: true,
    linguisticRules: {
        "е": "ё",
        "a": "ä",
        "o": "öó", // <--
        "u": "ü",
        "ss": "ß"
    },
});
```

Sincerely,
Sam.

**Comment by vjmartins** [comment]
Ok..But i have to do that to all portuguese accent charater, right?

```js
    linguisticRules: {
        "е": "éè",
        "a": "âáà",
        "o": "öóò", // <--
        "u": "ú"
    },`

**Comment by Calak** [comment]
yeah, think it as a map where the keys are characters with no diacritic, and values are diacritics variation that you would to handle.

**Comment by SamBrishes** [comment]
Version 1.0.0 contains an online generator, which allows building up an own tail.select bundle. Maybe It's a good idea to add linguistic rules in different languages to this generator too.

**Comment by Calak** [comment]
@SamBrishes yeah, I agree. `linguisticRules` could even be added in translation files.

**Comment by vjmartins** [comment]
I found this 
```js
const str = "Crème Brulée"
str.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
> "Creme Brulee"
```

Maybe it helps

https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript
