### ISSUE TITLE
Corret select-label height

### ISSUE THREAD

**Issue by vjmartins** [pytesNET/tail.select#98]
Hi..
I think i found a error.

I solve the problem put min-height in class .tail-select .select-label.

![Print_Error](https://user-images.githubusercontent.com/827692/62207477-23449000-b38c-11e9-8c01-dd55b9002c9f.jpg)

![Print_Error2](https://user-images.githubusercontent.com/827692/62207573-5850e280-b38c-11e9-9a0d-bae568f318dc.jpg)

**Comment by SamBrishes** [comment]
Hellow,

thanks for sharing this bug here. It is really strange, because there should always be a String inside the label element.

How did you trigger this issue? Can you please share your `tail.select` constructor?

Thanks.

Sincerely,
Sam.

**Comment by vjmartins** [comment]
`tail.select(".combobox", {animate: false,openAbove:false,search:true,searchFocus:true,width:"100%"});`

**Comment by SamBrishes** [comment]
Hmm... Kind of strange, can't rebuild this.

Anyway, thanks I'll add a `min-width` property, after @Calak has made his PR.

**Comment by Calak** [comment]
@SamBrishes *`min-height` ;)

**Comment by Calak** [comment]
@vjmartins can you show a jsfiddle that reproduce this bug?

**Comment by vjmartins** [comment]
i think not.. Im using html return by fetch..

I will check my css.

```js
var element = document.getElementById("element");
fetch(url, {method: "POST"})
.then(function(response) {return response.text()})
.then(function(html) {
      element.insertAdjacentHTML("beforeend", html);
      tail.select(".combobox", {animate: false,openAbove:false,search:true,locale:"pt",searchFocus:true,width:"100%"});})
.catch(function(err) {element.innerHTML = "Script Error";});
`

**Comment by Calak** [comment]
If you make a static page that contains this html and then try to remplace the select with `tail.select` does it reproduce?

Can you write (in this static page or into your ajax response) a `console.log(document.querySelector(".combobox").outerHTML);` between `element.insertAdjacentHTML(...)` and `tail.select(...)` ? Did you get the `<select>` element in the console? Can you post what's wrote into the console?

**Comment by vjmartins** [comment]
No.

Yes. 

```html
<select name="destinatario[]" class="combobox" style="width:90%">
<option value="0"></option>
<option value="60">Abel Jorge Rodrigues Cerqueira</option>
</select>

**Comment by Calak** [comment]
Ok, by default, css should have default `min-height` to handle this case on both `li.dropdown-option` items and on `.select-label`

And with your problem, I found another (in fact, re-found, but didn't posted about it I think)
This second problem came from the way option's labels (displayed text) and values (sent value) are handled.
I'll post an issue, but here's a fiddle that reproduce both your bug and mine: https://jsfiddle.net/Calak/f8L96cn1/

**Comment by SamBrishes** [comment]
Done in 0.6.0
